### ISSUE TITLE
Jekyll Planet?

### ISSUE THREAD

**Issue by phillipadsmith** [jekyll/jekyll-help#109]
No doubt this has already been mentioned or suggested somewhere, so please feel free to direct me to that spot to contribute... 

Quick questions/ideas: 

+ I'm often on the lookout for news & information (blog posts, articles, videos, etc.) about Jekyll and Jekyll-related projects (Prose.io, etc.), but there's no single "feed" of that information that I can subscribe to / check-in on from time-to-time

+ When I'm NOT actively hunting for news & information about Jekyll, I'm occasionally producing news & information that talks about Jekyll (or static site generators in general) and it would be great if there were a place to contribute that (e.g., http://phillipadsmith.com/tag/staticnewsapps/ )

The "News" section on the Jekyll site seems to just focus on releases. The "Resources" section might be the place, if pull requests are encouraged against it, but perhaps its best left as a curated "best of" resources list... 

Thus, I'm really asking about a less curated stream of what everyone is thinking and doing with Jekyll. Useful? Already underway? Best place for it?

Phillip.

**Comment by phillipadsmith** [comment]
@geraldb Amazing. Great stuff. I've starred the repo and will make a point of adding sources as I come across them. Many thanks for that; very useful! :)

**Comment by geraldb** [comment]
@phillipadsmith  Thanks for your kind words. If you're interested I've added you to the editors team - github will send you an invitation -  if you're interested you can change the planet config without pull request, for example, in your browser - you will have commit/write access). Cheers.

**Comment by phillipadsmith** [comment]
@geraldb Thanks! :)

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
