### ISSUE TITLE
category[0] is all lower case while tag[0] is case sensitive?

### ISSUE THREAD

**Issue by rdyar** [jekyll/jekyll-help#125]
I'm working up a page that lists all posts by tag, and another page is all posts by category.

I am getting category[0] returning the category name as all lowercase (even if it is Capitalized in the front matter) while tag[0] returns what I put into the front matter.

My front matter would look like:

```
---
category: Jekyll Update
tags: [Jekyll]
---
```

This seems wrong. I can capitalize with liquid, but it seems like it should be consistent.

It is possible that I am not using the category right I suppose. I am pretty confused by how it works sometimes. I am not using folders, other than to organize - right under the posts folder like:
_posts
          videos
          articles

i consider videos and articles to be types - not categories or tags and handle them myself with custom front matter.

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
