### ISSUE TITLE
Upgrading Jekyll from 1.4.3 to 2.3.0,  Error:  undefined method `glob_include?' for [".htaccess"]:Array

### ISSUE THREAD

**Issue by rubygeek** [jekyll/jekyll-help#128]
I updated my project from 1.4.2 to 2.3.0 and got this error: 

jekyll 2.3.0 | Error:  undefined method `glob_include?' for [".htaccess"]:Array

I don't have an .htaccess file nor do I use one, so this was puzzling. 

Turns out.. after some debugging and help from jaybe on irc, it was because I had the jekyll-sass gem. The later versions of Jekyll have sass support built in. Removing jekyll-sass from the Gemfile fixed it!

Hope this saves someone a few hours :)

**Comment by parkr** [comment]
This post has been migrated to Jekyll Talk: https://talk.jekyllrb.com/t/upgrading-jekyll-from-1-4-3-to-2-3-0-error-undefined-method-glob-include-for-htaccess-array/729
