### ISSUE TITLE
Weird regeneration problem - certain folder always capitalized.

### ISSUE THREAD

**Issue by rdyar** [jekyll/jekyll-help#130]
If i have a file named videos.html - not in the _posts folder.

with this:

```
---
permalink: /videos/
layout: default
title: Videos
description: 
---
<div class="container content">
        <div class="row">
            <div class="col-md-12">
hi
            </div>
        </div>
</div>    
```
no matter what I do the output folder comes out capitalized as Videos.
If I change the permalink to vvideos then it is correct as vvideos. I can rename the file something else and it doesn't change.

I have created a new jekyll site with nothing in it other than the the stock stuff - does the same thing.

I have also rebooted twice - no change. I also changed the title and still does it. No matter what I do if I have ```permalink: /videos/`` then I get the output folder as Videos.

I can put anything else in the permalink and it works fine. Just doesn't like the word videos.

Is there some sort of cache for ruby or jekyll that I need to clear?

I am on a windows 8 with the latest version of jekyll 2.3.0

Help.

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
