### ISSUE TITLE
Specifying multiple paths or types in Front Matter Defaults scope.

### ISSUE THREAD

**Issue by denilsonsa** [jekyll/jekyll-help#131]
The [documentation][1] does not explain how to do it, or if it even possible.

* How can I specify default values for pages matching more than one path? (e.g. both `about.html` and `index.html`)

* How can I specify multiple types? (e.g. setting the same value for both `posts` and `drafts`)

* Does the path support wildcards? How is it matched? (i.e. `index.html` matches this file on any directory or a single one? How to match it on any directory? Will `foobar/` match multiple files?)

----

My use-case: I want to set a value for all posts and drafts (since they are essentially the same).

I also wanted to set some values using wildcards such as `*.svg`, or `index.html` on any directory, or `foobar/*` (any file inside `foobar/`).

I'm stuck because I don't know if such things are possible, and neither how to write them.

[1]: http://jekyllrb.com/docs/configuration/#front-matter-defaults

**Comment by chimericdream** [comment]
I have the same question, but a different application. I have several collections that share some pieces of metadata. I'd _like_ to specify the default values for all of them at once, but cannot find anywhere that indicates whether this is possible.

Here's basically what I am looking for, but doesn't seem to work for me:

``` yml
defaults:
  - scope:
      path: ""
      type: [collectionA, collectionB]
    values:
      # values here...
```

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
