### ISSUE TITLE
Deploying to Heroku

### ISSUE THREAD

**Issue by AndyCErnst** [jekyll/jekyll-help#135]
Hello,
I've had a hell of a time trying to get Jekyll to run on Heroku. I followed the link for getting it to run with Rack 
http://blog.crowdint.com/2010/08/02/instant-blog-using-jekyll-and-heroku.html but it didn't work and the article is over four years old. Right now I'm getting "Push rejected, no Cedar-supported app detected" but at one point I could push to it but the logs said it crashed without giving a useful reason.

I don't know Rack or Ruby so this has been a very frustrating experience. I've tried several different tutorials on getting Jekyll to run on heroku but nothing has worked. Eventually I need to get this running on EC2 as well.

Even the static site files by themselves would be fine really.

My Procfile:
```
web: jekyll serve -p $PORT
```
My config.ru
```
require "rack/jekyll"

run Rack::Jekyll.new
```
My .gems
```
rack-jekyll
```
Full repo is here https://github.com/AndyCErnst/beat-the-banker-jekyll

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
