### ISSUE TITLE
Can't Install Jekyll - Updated Ruby Gems

### ISSUE THREAD

**Issue by mriccelli75** [jekyll/jekyll-help#137]
Here is the error I receive on the command line in my terminal on OSX 10.6.8 .

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
