### ISSUE TITLE
Is there a Jekyll-Discourse plugin yet?

### ISSUE THREAD

**Issue by oblakeerickson** [jekyll/jekyll-help#139]
[Discourse](http://eviltrout.com/2014/01/22/embedding-discourse.html) can be used to host comments on static sites and wasn't sure if there was a plugin for this yet? If not I'll probably work on one.

**Comment by parkr** [comment]
This issue has been migrated to Jekyll Talk: https://talk.jekyllrb.com/t/is-there-a-jekyll-discourse-plugin-yet/602
