### ISSUE TITLE
Using _config file to rename filenames but retain paths

### ISSUE THREAD

**Issue by mecrouch** [jekyll/jekyll-help#140]
Is there a way I can set the default permalink in my _config file to rename the HTML files for my site while retaining the existing directory structure of my Markdown project? Basically, my source project has a bunch of folders with Markdown files named readme.md (so they will be automatically displayed in GitHub when viewing the folder) like this:

- docs/readme.md
- docs/help/readme.md
- download/readme.md

But for my site, I'd like to rename them all index.html and retain the exisiting directory structure like this:

- docs/index.html
- docs/help/index.html
- download/index.html

It doesn't seem like I can rename just the file. I'm currently using a permalink variable in each MD file to set the path and the filename for the HTML on the site, but it would be much easier to maintain if I could just set the filename from the config file and tell it to keep the current path. Something like:

*/:dir/index.html* or */:path/index.html*

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
