### ISSUE TITLE
Jekyll + Docker = Awesome?

### ISSUE THREAD

**Issue by troyswanson** [jekyll/jekyll-help#141]
Hey everyone,

I just wanted to start a little discussion about using Jekyll in a Docker container. Has anyone done this? What kind of pitfalls should I expect? Should I use a dedicated web server? Which makes more sense: Nginx, or Apache? Will `jekyll serve` running WEBrick be good enough?

I'm approaching this as a guy who has never really run any Docker stuff in production, so any extra help on this would be awesome and will probably be helpful in the future. Thanks!

**Comment by jhabdas** [comment]
@troyswanson I think I've got what you're looking for [Simple websites with Jekyll and Docker](http://habd.as/simple-websites-jekyll-docker). In this post I show you how to use Windows or Mac to build a Jekyll-based docker site locally. Includes Dockerfile and instructions for deploying the image to a remote server via the command line.
