### ISSUE TITLE
How to install a theme?

### ISSUE THREAD

**Issue by RichardDooling** [jekyll/jekyll-help#142]
I have the pages being generated using this tutorial:

https://help.github.com/articles/using-jekyll-with-pages

But when I navigate to the pages, they are plain html. I see plenty of themes on the Internet but no instructions on the Jekyll site for installing themes?

If I use the page generator on github I can pick a theme for a single page but how to install a theme that works both locally and remotely. Thanks.

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
