### ISSUE TITLE
Searching

### ISSUE THREAD

**Issue by nausn97** [jekyll/jekyll-help#143]
On my blog when I search for a particular string it wont return any result.
second I want to implement sub string search for example : Blog Post are : "Naushad is Here"
and in navigation bar I am searching for a content like : "shad" 
it should return a result because "shad" is present in "Naushad" 

so can anyone help me how to implement this functionality on my blog. which plugin I should use and how to migrate this feature.

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
