### ISSUE TITLE
Breadcrumb plugin

### ISSUE THREAD

**Issue by LeG3nDz** [jekyll/jekyll-help#146]
Hello community,

I am looking for a breadcrumb plugin that allow myself to do this : Home / Blog / Category / Title page

I tried several solutions found on the net, but none works :( :

* http://biosphere.cc/software-engineering/jekyll-breadcrumbs-navigation-plugin
* https://github.com/socrata/labs-common-jekyll/blob/master/with-breadcrumbs.html (not the path name)
* http://stackoverflow.com/questions/9612235/what-are-some-good-ways-to-implement-breadcrumbs-on-a-jekyll-site

Do you have a reliable solution ?

Thank you so much :)

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
