### ISSUE TITLE
Pagination not working as expected

### ISSUE THREAD

**Issue by wolfej4** [jekyll/jekyll-help#147]
I am trying to use pagination, but being new to all of this doesn't help and looking for answers here and on Google are proving itself a challenge.

All I would like to do is split up my blog to separate pages.

I have this so far on my index:

{% for post in paginator.posts %}
--Post Title--
{% endfor %}

And the paginate variable is set to 5 in my config.

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
