### ISSUE TITLE
Jekyll-Paginate generates no pages

### ISSUE THREAD

**Issue by emeQee** [jekyll/jekyll-help#149]
I have a Jekyll instance with currently 4 blog posts. When I set paginate, the root gives me the number of posts per page (`paginate: 2`) but I always get the last 2 posts on index.html. The pagination link will show previous but the page files (`paginate_path`) are not generated. To test the pagination I have following settings.

    paginate: 2
    paginate_path: "seite-:num"

Even though I have a much more complex code with if statements to control pagination etc, the general idea of the template is as follows:

    {% for post in paginator.posts %}
    {% include article.html %}
    {% endfor %}

    <p class="hidden">Seite: {{ paginator.page }} von {{ paginator.total_pages }}</p>
    <ul class="pager">
        {% if paginator.previous_page %}
        <li class="previous">
            <a href="{{ paginator.previous_page_path | prepend: site.baseurl | replace: '//', '/' }}"><i class="fa fa-chevron-left"></i> Neuer</a>
        </li>
        {% endif %}
        {% if paginator.next_page %}
        <li class="next">
            <a href="{{ paginator.next_page_path | prepend: site.baseurl | replace: '//', '/' }}"><i class="fa fa-chevron-right"></i> &Auml;lter</a>
        </li>
        {% endif %}
    </ul>

What do I do wrong?

Here are the versions I have on my system:

    $ gem list | grep jekyll
    jekyll (2.4.0, 2.3.0, 2.1.1, 2.0.3)
    jekyll-coffeescript (1.0.1, 1.0.0)
    jekyll-date-format (1.0.1, 1.0.0)
    jekyll-gist (1.1.0)
    jekyll-page-hooks (1.3.1, 1.2.0)
    jekyll-paginate (1.0.0)
    jekyll-sass-converter (1.2.1, 1.2.0, 1.0.0)
    jekyll-sitemap (0.6.0, 0.5.1, 0.4.1)
    jekyll-watch (1.1.1, 1.1.0, 1.0.0)

My code is on [bitbucket](https://bitbucket.org/emin/dokudo-blog-jekyll/).

**Comment by corysimmons** [comment]
bump?

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
