### ISSUE TITLE
Jekyll not recognising file changes on 'build' when run in a Vagrant VM

### ISSUE THREAD

**Issue by matt-bailey** [jekyll/jekyll-help#151]
As requested, I'm moving this issue here from [one I raised](https://github.com/jekyll/jekyll/issues/2923) on the main Jekyll repo.

I'm using Jekyll for the first time to create a personal blog. I do all my development in Vagrant VMs (for the consistent dev environment and clean host machine), so I've done the same with Jekyll.

The issue I'm having is that, fairly frequently, Jekyll doesn't appear to recognise when files have been updated when I `jekyll build` - the `_site` directory is regenerated, but with old code. It's like Jekyll is using some 'cached' version of the source code, even though I know this isn't the case.

This applies to all file types - .md, .html, .scss etc. I tried deleting the `.sass-cache` directory on the off-chance it would make a difference to CSS changes, but it didn't. It can take a minute or so before changes start to be recognised. Then, after another minute or so they stop being recognised again for a while.

On the other thread @parkr said that it "Sounds like your _site is being synced more slowly than jekyll is rebuilding it". I know that Vagrant syncs a directory between the VM and my host machine so this does sound plausible. He then asked "Can you use something like haproxy and forwarded ports to run the server from vagrant as well as the jekyll project?" As a mostly frontend developer this is already pushing my technical skills to the limit, so I'm not really sure I understand this. However, As far as I was aware the VM is already running the server and forwarding the ports to my host machine.

@troyswanson asked me to say a bit more about my set up, so here it is:

- OS X 10.9.4
- Virtual Box 4.3.12
- Vagrant 1.6.5
- [PuPHPet GUI](https://puphpet.com/) for VM config set up
- Ubuntu Trusty 14.04 LTS x64
- Forwarded ports: host `8188`, guest `22`
- File system: NFS
- Server version: Apache/2.4.10 (Ubuntu)
- VHost port: `80`
- PHP 5.6
- SSH `ForwardAgent` set to `yes` on the host machine
- Ruby 1.9.3p547
- Node 0.10.31
- Jekyll 2.3.0
- I'm also using Grunt to do a few things first (imagemin, uglify etc.) before running `jekyll build` as the last task (using [grunt-shell](https://github.com/sindresorhus/grunt-shell))

I'm not sure what else to tell you. If there's anything else it would help to know please do let me know.

Sods law, at the moment I can't reproduce the issue. But you can be sure the next time I sit down to do a bit of dev it'll reappear again ;)

**Comment by jamesdh** [comment]
I'm seeing something similar but just on OS X - no vagrant at all.  I updated my _includes/header.html file (which is used by my default layout). The update gets reflected in the generated HTML under `_site` on all relevant pages. However when running `bundle exec jekyll serve` the update is only reflected in my main index page. Any generated post pages are still appear with the old header when browsing to them, despite the fact they show the correct code under `_site`!

I've repeatedly tried clearing my browsers cache, using incognito mode, and completely resetting all settings, and it's still showing the old version of the post pages. Is it possible that `jekyll serve` somehow caches some generated pages and it's not correctly reflection changes?

**Comment by tduchateau** [comment]
For information, I'm hitting the same issue but using Boot2Docker 1.7 (based on VirtualBox 4.3.26) on Win8.1.

Even if the `--force_polling` option "fixed" the auto-regeneration issue (see https://github.com/jekyll/docker-jekyll/issues/14), I realized as @matt-bailey, that sometimes the `_site` directory is regenerated, but with old code. I know that the "sometimes" word sucks :-/

I've tried to manually delete the `_site` directory, with and without polling, but nothing seems to be stable. I ended up using my local install of Jekyll in order to be sure of what is generated.

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
