### ISSUE TITLE
How to create multi-lang article page? maybe i18n related...

### ISSUE THREAD

**Issue by yarcowang** [jekyll/jekyll-help#153]
I want to create a page which may both includes english and chinese version, which may have in the following layout:

__Title__
__English Content On The Left__  ------  __Chinese Version on Right___
__Date__

And the content should comes from:
_posts/2014-09-18-test.en.md -- for english
_posts/2014-09-18-test.cn.md -- for chinese

And if post only have one version, it should also work:
_posts/2014-09-18-test.md

So, what is the best way to achieve this?

**Comment by iamsebastian** [comment]
Maybe this would not work:
http://ecommerce.shopify.com/c/ecommerce-design/t/testing-if-a-file-exists-29624

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
