### ISSUE TITLE
Question about the "where" filter

### ISSUE THREAD

**Issue by budparr** [jekyll/jekyll-help#155]
Am I crazy, or was it possible at one point to use the "where" filter to exclude items with a particular value, like this:

Documented usage:
```
{{ site.members | where:"graduation_year","2014" }}
```
and not-documented, but I thought once worked:
```
{{ site.members | where:"graduation_year", -"2014" }}
```
to pull members who graduated in any year NOT 2014.

It seems to me like I used this once, but it doesn't work now.

**Comment by parkr** [comment]
/cc #156. This isn't currently a feature.

This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
