### ISSUE TITLE
How to list all posts without a specific tag?

### ISSUE THREAD

**Issue by footoredo** [jekyll/jekyll-help#156]
If I want to list all posts with a specific tag, I can use `{{ site.tags.TAG }}`. What should I do if I want all without it?

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
