### ISSUE TITLE
Cannot configure jekyll with github-pages

### ISSUE THREAD

**Issue by b-grider** [jekyll/jekyll-help#158]
I installed github-pages, and attempted to run Jekyll with Bundler in a way that matches the github pages build server, but I keep getting this error.

![jekyllerror](https://cloud.githubusercontent.com/assets/6391122/4397892/7a3f3452-444a-11e4-8175-793d82b4d322.jpg)

I've seen a few issues that appear related, but nothing I've tried works. Ideas anyone?

**Comment by bmmathe** [comment]
I'm having the same issue and don't want to install Python to use Pygment and GitHub Pages only supports Rouge.
