### ISSUE TITLE
Custom sitemap overwritten in production

### ISSUE THREAD

**Issue by ndarville** [jekyll/jekyll-help#159]
(Via hafniatimes/issues#12.)

I have a [manual sitemap file](https://github.com/hafniatimes/hafniatimes.github.io/blob/master/sitemap.xml) I wish to use for my site in production. For some reason, though, I get [a different output](http://hafniatimes.com/sitemap.xml) in production than in my local `_site` folder.

I’ll post the content and output in a separate comment.

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
