### ISSUE TITLE
Filtre category in pagination

### ISSUE THREAD

**Issue by LeG3nDz** [jekyll/jekyll-help#161]
Hi community !

I've add a pagination on my blog part, displaying all categories except "portfolio". There are not posters but still create a "post invisible" when I post in the "portfolio".

If you want clone my projet : https://github.com/LeG3nDz/v3.stephane-richin.lan

Could you tell me/help me what I did wrong ?

Thank you so much !

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
