### ISSUE TITLE
How to get offline documentation with the command docs?

### ISSUE THREAD

**Issue by KabbAmine** [jekyll/jekyll-help#166]
Hi.

As I understood the command `docs` is for viewing *jekyll* documentation offline, but I don't know how to use it.

This is what I get for `jekyll docs`:

                Source: /var/lib/gems/2.1.0/gems/jekyll-2.4.0/site
       Destination: /var/lib/gems/2.1.0/gems/jekyll-2.4.0/site/_site
      Generating... 
    jekyll 2.4.0 | Error:  No such file or directory @ dir_chdir - /var/lib/gems/2.1.0/gems/jekyll-2.4.0/site/

Note that I'm new to ruby and gem's system, so maybe I've missed something.

Configuration:
- Jekyll 2.4.0
- Xubuntu 14.04

**Comment by gideonite** [comment]
I'm still having this problem. I'm using:

jekyll 2.5.3
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
gem 2.4.5

When I run `jekyll docs` from my home directory I get this error. 

```
Configuration file: none
            Source: /home/gideon/.gem/ruby/2.2.0/gems/jekyll-2.5.3/site
       Destination: /home/gideon/.gem/ruby/2.2.0/gems/jekyll-2.5.3/site/_site
      Generating... 
jekyll 2.5.3 | Error:  No such file or directory @ dir_chdir - /home/gideon/.gem/ruby/2.2.0/gems/jekyll-2.5.3/site/
```

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
