### ISSUE TITLE
Cannot load rdiscount.so (markdown processing)

### ISSUE THREAD

**Issue by gg8345** [jekyll/jekyll-help#169]
I'm trying to use Octopress to generate my first post, but maybe this is something Jekyll can answer as it's used as the basis for Octopress.. Still can't get it to process the markdown post..

I'm running Windows 7 64 bits, installed Ruby 1.9.3 and the latest Octopress from the git repository (from today).

I've verified that rdiscount is correctly installed (through the bundle install).
rdiscount is 2.1.7.1. rdiscount.so is in ext/rdiscount.so..

Anybody has an idea of what is going wrong ? Thanks.

> rake generate
## Generating Site with Jekyll
identical source/stylesheets/screen.css
Configuration file: C:/website/octopress/_config.yml
            Source: source
       Destination: ../production/public/
      Generating...
[31m  Dependency Error:  Yikes! It looks like you don't have rdiscount or one o
f its dependencies installed. In order to use Jekyll as currently configured, yo
u'll need to install this gem. The full error message from Ruby is: 'cannot load
 such file -- rdiscount.so' If you run into trouble, you can find helpful
 resources at http://jekyllrb.com/help/! [0m
[31m  Conversion error: Jekyll::Converters::Markdown encountered an error conve
rting '_posts/2008-10-23-tt.md/#excerpt'.[0m
[31m  Conversion error: rdiscount[0m
[31m             ERROR: YOUR SITE COULD NOT BE BUILT:[0m
[31m                    ------------------------------------[0m
[31m                    rdiscount[0m

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
