### ISSUE TITLE
Any idea of how get Jekyll work under c9.io?

### ISSUE THREAD

**Issue by isorna** [jekyll/jekyll-help#170]
Hi there, I'm a big fan of c9.io ide, as I'm working with a Chromebook, but there seems I'm not doing something well, as I can't get Jekyll (or Poole) working under my c9 project.

It's there anyone who managed to achieve it?

Regards

**Comment by bvsatyaram** [comment]
This didn't work for me. The following worked:

```
gem install jekyll
jekyll new my-awesome-site
cd my-awesome-site
jekyll serve --host $IP --port $PORT --baseurl ''
```
