### ISSUE TITLE
Jekyll doesn't respect line breaks

### ISSUE THREAD

**Issue by weilawei** [jekyll/jekyll-help#171]
The Markdown syntax documentation on Daring Fireball says:

"When you do want to insert a <br /> break tag using Markdown, you end a line with two or more spaces, then type return."

Doesn't work.

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
