### ISSUE TITLE
Best mechanisms for single source in multiple locations

### ISSUE THREAD

**Issue by hamishwillee** [jekyll/jekyll-help#176]
Consider the requirement for a document site with one more more sections that have common topics. Each section has its own TOC and can navigate to the next/prev items in that TOC using prev->next buttons. The documents may have slightly different rendering in each section (and of course a different TOC/next/prev). There should be a single "content" document for the common content.

The obvious way to implement something like this is to have the "common content" source as an *_include*. Then have "stub" articles for each TOC item that imports it. This would work nicely and allow me to feed in "version specific" configuration in the front matter.

Are there any other ways that people have achieved this? For example, is there a way to automatically copy appropriate documents into specified locations at build time (from within Jekyll)?

Thank you!

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
