### ISSUE TITLE
Non-home pagination either doesn't work or messes up navigation

### ISSUE THREAD

**Issue by creativedutchmen** [jekyll/jekyll-help#177]
Consider the following url structure:

`domain/` for the homepage (static)
`domain/news/` for the list of posts (paginated)
`domain/news/page-n/` for page n of posts

To my understanding, there are two ways I can structure the `news` page: either by using `news.html` or by using `news/index.html`. The first method will render the pagination in the home layout - and return empty on the `news.html` loop.

No problem, let's try the `news/index.html` method. Pagination now works, but every paginated page now shows up in the navigation - making it look like `news | news | news | news | news`. Not good either.

So, my question is: is there a way to provide pagination on a page other than home, without messing up the navigation?

**Comment by TheCodeDestroyer** [comment]
I have the same issue... Any news on this?

**Comment by kleinfreund** [comment]
Pagination will only work on index.html files and with no filtered group of content like categories, tags, etc. I'm not sure what's messing up your last example, though.

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
