### ISSUE TITLE
blog creation issue using Jekyll

### ISSUE THREAD

**Issue by bettygcp** [jekyll/jekyll-help#181]
I went ahead and wanted to create my new blog with the name myblog, as per the instructions on the Jekyll website: http://jekyllrb.com/docs/quickstart/
///#
user@computer:~$ jekyll new myblog
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in require': iconv will be deprecated in the future, use String#encode instead. WARNING: Could not read configuration. Using defaults (and options). No such file or directory - new/_config.yml Building site: new -> myblog /usr/lib/ruby/vendor_ruby/jekyll/site.rb:126:inchdir': No such file or directory - /home/user/new/ (Errno::ENOENT)
from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:126:in read_directories' from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:98:inread'
from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:38:in process' from /usr/bin/jekyll:250:in'
///

Please help me out.
Thanks

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
