### ISSUE TITLE
How does one list pages in a directory

### ISSUE THREAD

**Issue by bloudraak** [jekyll/jekyll-help#182]
I have a couple of folders with documents.
  
    dir1\page1.md
    dir1\page2.md
    dir1\page3.md
    dir1\dir2\page4.md
    dir1\dir2\page5.md
    dir1\dir2\page6.md
    dir3\page7.md
    dir3\page8.md
    dir3\page9.md

For each folder, I'd created an `index.html` in each directory, including `dir1`, `dir1\dir2` and `dir3` with some custom content.  However, I'd like to generate list to each page inside the folder (but not subdirectories) similar to 

    <h2>dir1 specific header</h2>
    <p>dir1specific content. bla bla bla.</p>
    <h3><a href="page1.html"Page1</a></h3>
    <p>excerpt from Page1</p>
    <h3><a href="page2.html">Page2</a></h3>
    <p>excerpt from Page2</p>
    

I added this to `index.html` in dir1

    <h2>dir1 specific header</h2>
    <p>dir1specific content. bla bla bla.</p>
    {% for page in site.pages %}
    <h3><a title="{{ page.title }}" href="{{ page.url | prepend: site.baseurl }}">{{ page.title }}</a></h3>
    <p>{{page.excerpt}}</p>
    {% endfor %}     

However, it shows all the pages from `page1.md` to `page9.md` rather than `page1` to `page3`. Is there a built-in way to limit the pages being listed to only have those in the same folder?

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
