### ISSUE TITLE
Page build failure

### ISSUE THREAD

**Issue by tjmapes** [jekyll/jekyll-help#185]
I'm sorry if this is a duplicate but I'm new to SCSS and keep getting emailed with this when trying to commit any changes:

> The page build failed with the following error:
> The file `blog/css/main.scss` contains syntax errors. For more information, see 
> https://help.github.com/articles/page-build-failed-markdown-errors.
> If you have any questions please contact us at https://github.com/contact.

My compiler is telling me the following:

> Invalid CSS after "-": expected number or function, was "--"

**Comment by ffffranklin** [comment]
FYI layout:null doesn't seem to work for me.  If you're like me or @lucachaco  you moved your jekyll instance to a sub directory and appended a `source` property to your `_config.yml` that points to it.  Unfortunately GitHub Pages doesn't like that.  It reserves the `source` attribute to point to your "top-level directory"  (see https://help.github.com/articles/using-jekyll-with-pages/#configuring-jekyll).  

It appears that the only solution is to move the site source back to the top-level (**pro-tip** or pivot to another repo and deploy only static files using a CI platform like Facebook: https://github.com/facebook/react/commits/gh-pages).

**Comment by parkr** [comment]
@ffffranklin Yes, `source` is always set to the root of your repo. If you would like a subdirectory, create a new repo with the name of the desired subdirectory and push your code to the root of your new repo on the `gh-pages` branch. :+1:
