### ISSUE TITLE
Stop Jekyll Wrapping Images in P Tags

### ISSUE THREAD

**Issue by juicymark** [jekyll/jekyll-help#188]
Can somebody advise on how it is possible to stop jekyll wrapping p tags around image tags using markdown

Regards

Mark

**Comment by ortonomy** [comment]
Except kramdown wraps everything in `<p>` tags, regardless of its inline or block level:

> The contents of a blockquote are block-level elements. This means that if you are just using text as content that it will be wrapped in a paragraph. 

Sauce: https://kramdown.gettalong.org/syntax.html

**Comment by henrikhelmers** [comment]
Some of the reasoning in here doesn't make sense. According to the [HTML5 spec](https://www.w3.org/TR/html5/grouping-content.html#the-figure-element) the figure element can contain a wide variety of things, more than would fit in an image tag.

> The element can thus be used to annotate illustrations, diagrams, photos, code listings, etc.

The markdown renderer assumes that it exists in a vacuum, whereas it actually is surrounded by Jekyll layouts with plenty of capability. I wish Kramdown made an effort to get along with the other parts of Jekyll.
