### ISSUE TITLE
Issue with Jekyll Mercenary

### ISSUE THREAD

**Issue by ericthor** [jekyll/jekyll-help#189]
Running Jekyll 2.5.1 with Ruby 2.0 . When I run `jekyll s` or `jekyll w`
```
Error output
/Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.4/lib/mercenary.rb:20:in `program': cannot load such file -- mercenary/program (LoadError)
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.1/bin/jekyll:20:in `<top (required)>'
	from /usr/bin/jekyll:23:in `load'
	from /usr/bin/jekyll:23:in `<main>'
```

My Gemfile. I've commented out the other gem still getting error.
```
source 'https://rubygems.org'
gem 'jekyll'
# gem 'jekyll-assets'
# gem 'autoprefixer-rails'
# gem 'jekyll-press'
# gem 'jekyll-sitemap'
# gem 'jekyll-mentions'
# gem 'jekyll-tagging'
# gem 'ruby-oembed'
# gem 'mercenary'
```
bunder.rb file
```
require 'rubygems'
require 'bundler/setup'
require 'jekyll'
# require 'jekyll-assets'
# require 'autoprefixer-rails'
# require 'jekyll-press'
# require 'jekyll-sitemap'
# require 'jekyll-mentions'
# require 'jekyll/tagging'
# require 'oembed'
```

I'm not too experienced with Ruby, but I noticed in the Gemfile.lock under Jekyll in requires lists       mercenary (~> 0.3.3) and then later on lists " mercenary (0.3.4)" separately.

If I run `bundle exec jekyll s` I receive no errors. Maybe it's the way I'm calling / requiring these gems.

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
