### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by troyswanson** [jekyll/jekyll-help#195]
Despite asking folks to search before posting, it seems like we get a lot of dupes. Maybe we can set up a list of FAQs in the README? What do y'all reckon?

/cc @jekyll/help

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!

**Comment by parkr** [comment]
Lol. My blanket response. FAQ should just be in the docs?
