### ISSUE TITLE
Need CRLF preservation on Windows

### ISSUE THREAD

**Issue by camkego** [jekyll/jekyll-help#196]
Hopefully the bad W word doesn't leave me without feedback.

Jekyll 2.5.1 and Kramdown currently turn CRLF line endings in LF,
this would be fantastic, except I am using features of IE that require CRLF line endings.
[Specifically 'Mark of the web']

You would be correct to say, 'gross', but I am required to find a solution anyway]

Is there a suggested, or 'best-way' to do this?

I need to make sure my Jekyll output on Windows either preserves CRLF [not currently],
or converts line-endings to CRLF.

Thanks in advance

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
