### ISSUE TITLE
jekyll serve

### ISSUE THREAD

**Issue by ragwing** [jekyll/jekyll-help#200]
I am trying to load jekyll server to view using http://localhost:4000
But keep getting this.

```
jekyll serve
/var/lib/gems/2.1.0/gems/jekyll-2.5.1/lib/jekyll.rb:166:in `<top (required)>': undefined method `gracefully_require' for Jekyll::Deprecator:Class (NoMethodError)
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /var/lib/gems/2.1.0/gems/jekyll-2.5.1/bin/jekyll:6:in `<top (required)>'
    from /usr/local/bin/jekyll:23:in `load'
    from /usr/local/bin/jekyll:23:in `<main>'
```

I have checked all dependencies installed, running Ubuntu 14.10
Something I must have done incorrectly but not sure what.
Thanks

**Comment by troyswanson** [comment]
Oh, yeah. Definitely don't install Jekyll using distro specific package managers like `apt-get` or `yum`.

Use `gem` to manage your Jekyll installation.

**Comment by GordonGustafson** [comment]
Uninstalling jekyll with `apt-get` and reinstalling it with `gem` fixed a similar problem for me.
