### ISSUE TITLE
Build error after upgrading to Yosemite

### ISSUE THREAD

**Issue by milesgrimshaw** [jekyll/jekyll-help#203]
I get the following error on `jekyll build` and have tried reinstalling Ruby, Rails, gems etc. 

WARN: Unresolved specs during Gem::Specification.reset:
      posix-spawn (~> 0.3.6)
      ffi (>= 0.5.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Users/milesgrimshaw/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-2.5.2/bin/jekyll:21:in `block in <top (required)>': cannot load such file -- jekyll/version (LoadError)
	from /Users/milesgrimshaw/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:18:in `program'
	from /Users/milesgrimshaw/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jekyll-2.5.2/bin/jekyll:20:in `<top (required)>'
	from /usr/bin/jekyll:23:in `load'
	from /usr/bin/jekyll:23:in `<main>'

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
