### ISSUE TITLE
Post layout isn't working

### ISSUE THREAD

**Issue by PaulTuraew** [jekyll/jekyll-help#205]
I followed all the directions on creating a .md post (e.g. 2011-12-31-new-years-eve-is-awesome.md), putting it in the _posts folder and included the YAML front matter and it still won't recognize the layout. I am currently running it on my local server. 

When I look in my "site" folder and actually see the HTML code for the post, Jekyll is putting the front matter in the content <p> elements. 

Any suggestions? Thank you!

**Comment by ghost** [comment]
I had a similar problem, but found out the layout defined in YAML front matter had a wrong spelling!
