### ISSUE TITLE
Note block

### ISSUE THREAD

**Issue by zemadmat** [jekyll/jekyll-help#206]
Hi,
I have seen the Jekyll web site and i love the idea to have hint, note warning/ alert box but if i just type markdown note: it does not render like the jekyll site.

how is it possible to have a such box ? also like the ProTip box.

Cheers

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
