### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by FabianCernota** [jekyll/jekyll-help#207]
Hey, 
i get the following error while install  jekyll via gem:

ERROR:  Error installing jekyll:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:1:in `<main>'

Thanks
Fabian

**Comment by KitN** [comment]
Thanks, bradhowes. I had trouble with `gem install jekyll` but `apt-get install make` worked for me on Debian.

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
