### ISSUE TITLE
jekyll 2.5.2 | Error:  undefined method `in_dest_dir' for nil:NilClass

### ISSUE THREAD

**Issue by joethephish** [jekyll/jekyll-help#208]
Our website is built on Jekyll, originally version 1.x.

I just got a new laptop (MacBook Pro with Yosemite), so installed Jekyll from fresh. Unfortunately when attempting to build our site, I get the following error:

```
jekyll 2.5.2 | Error:  undefined method `in_dest_dir' for nil:NilClass
```

Any suggestions? Is there something I need to do to migrate, or something I can do to diagnose the problem?

Many thanks!

**Comment by johnpflyer74** [comment]
I'm new to **GitHub** and **jekyll**, so please forgive any rookie behavior on my part. 

I am testing out a plugin ( [`jekyll-thumbnailify`](https://github.com/10io/jekyll-thumbnailify) ) and I am receiving the exact same error as **joethephish**. The only difference is that I have slightly newer versions of **gems** and **jekyll**:

```
Generating...
/usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/static_file.rb:40:in `destination': undefined method `in_dest_dir' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/cleaner.rb:43:in `block in new_files'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:477:in `block (2 levels) in each_site_file'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:476:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:476:in `block in each_site_file'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:475:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:475:in `each_site_file'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/cleaner.rb:43:in `new_files'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/cleaner.rb:24:in `obsolete_files'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/cleaner.rb:15:in `cleanup!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:308:in `cleanup'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:52:in `process'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

I see that **joethefish** came to the conclusion that "...  it was something to do with the fact that StaticFile objects now require the `site` property to be set in their constructor." I poked around to try and figure out how to do that, but I haven't had any luck.

Could one of you guys help me understand how to pass the `site` to the StaticFile subclass of the plugin?

I'm not even sure if my team is going to use `jekyll-thumbnailify`, but I've spent so much time trying to figure out how to fix the issue that I need to see it through to the end.

Oh, and I don't know if this is relevant, but I used **Home Brew** to install `imagemagick` today, so I believe I have the latest version.

**Comment by joethephish** [comment]
Here's what I did (albeit in my own hacked plugin that is now a bit different from `jekyll-thumbnailify`):

Line 65: Add site as first parameter:

    static_file = ImageStaticFile.new(site, thumbnail, image_folder, thumbnail_name)

Line 122: Take this new parameter to the `ImageStaticFile` subclass:

    def initialize(site, image_src, image_dest_dir, image_dest_name)
        @site = site

**Warning: I have near-zero experience with Ruby, and I do not understand much of the way Jekyll works, so this may be a terrible awful hack, and I wouldn't be surprised if it didn't work ;-) Use at your own risk!**

That said, I hope it helps you!

**Comment by johnpflyer74** [comment]
That worked! Thanks for the help.

Hack or not, it did the trick. What I'm learning is that it is more important to understand the principals of coding and less so to understand the language. 

Cheers.
