### ISSUE TITLE
Installing Jekyll: ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by alexwoolley** [jekyll/jekyll-help#209]
Hello,

Completely new to Jekyll, so apologies if this is a stupid question. After running 

`gem install jekyll`

I get the following error message:

`Building native extensions.  This could take a while...`
`ERROR:  Error installing jekyll:`
    `ERROR: Failed to build gem native extension.`

```
``/usr/bin/ruby2.1 -r ./siteconf20141210-5038-1u40f3s.rb extconf.rb``
```

`mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h`

`extconf failed, exit code 1`

`Gem files will remain installed in /var/lib/gems/2.1.0/gems/fast-stemmer-1.0.2 for inspection.`
`Results logged to /var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/fast-stemmer-1.0.2/gem_make.out`

Seems like the commonest solution to this is to run

`sudo apt-get install ruby1.9.1-dev`

But this ain't solving the problem for me -- anyone got any tips..?

**Comment by dhanvi** [comment]
:+1: for the issue this saved my day too :smile:

**Comment by femontanha** [comment]
Helps me too! Thanks all

**Comment by joaobentes** [comment]
Thank you. Help me too!

**Comment by redtrumpet** [comment]
Thanks, this solved my problem!

**Comment by schmanat** [comment]
Thanks too, solved my problem!

**Comment by tshriver** [comment]
Thanks!

**Comment by sara-02** [comment]
Tried the above solution, I am still getting the error

**Comment by dylan-cooper** [comment]
Thanks! Also solved my problem.  I have ruby 2.2 installed, so I needed

```
sudo apt-get install ruby2.2-dev
```

as ruby-dev installed it for ruby 1.9.3

**Comment by cesards** [comment]
:+1: Nice! @sondr3

**Comment by marceloavan** [comment]
useful, thanks

**Comment by HieronyM** [comment]
Useful.

**Comment by atru** [comment]
@sara-02, I had the same problem. Running `sudo apt-get install make` solved the issue for me. Though I had problems with finding the right version of Jekyll (only `sudo gem install jekyll -v '1.5.1'` worked for my ruby 1.9.1 environment).

**Comment by masoudgs** [comment]
thanks

**Comment by rgbm21** [comment]
Ran into this problem in linux mint 

```

Building native extensions.  This could take a while...
ERROR:  Error installing jekyll:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.2 -r ./siteconf20160207-29276-67usj.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.2.0/gems/ffi-1.9.10 for inspection.
Results logged to /var/lib/gems/2.2.0/extensions/x86_64-linux/2.2.0/ffi-1.9.10/gem_make.out
```

My ruby version:

`ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux-gnu]`

**Comment by sondr3** [comment]
Do you have all the build tools as well? GCC, make and so on?

**Comment by ragmha** [comment]
@sondr3  I have fixed it following this http://stackoverflow.com/questions/34521806/installing-jekyll-on-ubuntu-14-04/34523631#34523631 :+1:
