### ISSUE TITLE
How do I auto-start jekyll?

### ISSUE THREAD

**Issue by lewispgj** [jekyll/jekyll-help#212]
First I have to commend the jekyll team on a great product! Installation and usage is extremely easy, for the most part. Thanks for all of your hard work!

That said, after nearly two-hours of very-frustrated searching, I can't find any tips on how to auto-start Jekyll. It's obviously not reasonable for me to have to type into terminal "jekyll serve --source /var/www/my-awesome-site" every single time my server needs to reboot. So how the heck do I auto-start jekyll? I'm new to upstart but over an hour of scripting hasn't yielded any results.

Can someone please breathe some life into this process before I have to switch to another blogging solution, simply because I can't get it to auto-start? Thanks!!!!

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
