### ISSUE TITLE
Jekyll Pagination

### ISSUE THREAD

**Issue by juicymark** [jekyll/jekyll-help#213]
Hi

I am currently transferring a blog from wordpress to jekyll  for a friend of mine and need some help with how to create pagination links for the blog posts.

I need the pagination to show first & last Pages along with a selection of the pages in between the first and last pages

eg..

1 2 3 4 5 ... 15
1 2 3 4 5 6 ... 15
1 ... 7 8 9 10 11 ... 15 

Does anyone on here know how i can achieve this without the use of a plugin??

Regards

Mark

**Comment by parkr** [comment]
I believe @rodaine managed this: https://github.com/rodaine/rodaine.github.io/tree/master/_includes/pagination

**Comment by rodaine** [comment]
There is plenty of room for improvement though :)
