### ISSUE TITLE
YAML configuration problem when using "gh-pages"

### ISSUE THREAD

**Issue by ajlohman** [jekyll/jekyll-help#215]
I'm getting errors on the settings page when pushing things to github:

"Your page is having problems building: Page build failed. For more information, see https://help.github.com/articles/using-jekyll-with-pages#troubleshooting."

So I figured my "url" and "baseurl" are wrong in my _config.yml file.

My _config.yml file:

========================================
#Syntax highlighting
highlighter:         pygments

# Permalinks
#Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

#Setup
title:               Magento design
tagline:          Magento designs and such...

#Local
#http://localhost:4000/magentoproto/homepage-v1/

# This is what I can't get to work? Doesn't work locally or on github
#url:                 https://github.corp.ebay.com/pages/ajlohman/magentoproto
#baseurl:         /pages/ajlohman/magentoproto

#This works locally but error when pushed to github
#url:                 http://ajlohman.github.io/magentoproto
#baseurl:         /magentoproto

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed

========================================

Any help would be greatly appreciated! thanks,

**Comment by troyswanson** [comment]
I mentioned it [here](https://github.com/jekyll/jekyll-help/issues/226#issuecomment-68659540), but I'll mention it again. Use [GitHub Pages Metadata](https://help.github.com/articles/repository-metadata-on-github-pages/). It's immensely helpful in situations like this.
