### ISSUE TITLE
Jekyll suddenly not regenerating on two machines ...

### ISSUE THREAD

**Issue by RonJeffries** [jekyll/jekyll-help#216]
SEE COMMENT BELOW. Probable bug in regeneration logic.

Jekyll has generally automatically regenerated after I run "jekyll serve". This weekend, it stopped. More interestingly, it stopped on both my MacBook Air and my iMac. I am running the same site on both, pulling from my rj-com repo. 

So, I'm imagining that there could be something wrong with my site, perhaps in a plugin? I've got a few, including a couple that my colleague and I wrote. The site generates OK the first time and after that nothing happens. Advise me, please.

**Comment by troyswanson** [comment]
Alrighty then. Let us know if you need any more help!
