### ISSUE TITLE
Jekyll Removing Changes To Edited Files

### ISSUE THREAD

**Issue by szier1** [jekyll/jekyll-help#219]
Hello,

So far Jekyll has been fun to use and I am starting to get more into it rather than creating basic posts. However, I have made various changes to files such as the main.scss or the index.html in the "_site" folder and find these edited files to display correctly while my server is running, but automatically return to there original state when I restart/regenerate Jekyll. In other words, I completely lose all of my changes. This is very frustrating as I intend to make many UI/functional changes on my site. Has anyone experienced similar problems? I appreciate any advice you can give! 

Thank you!

**Comment by troyswanson** [comment]
@szier1 You should consider the `_site` folder untouchable. The code in Jekyll specifically removes everything in the `_site` folder every time it is regenerated. Depending on the platform you are using, there are ways to have your web browser reload once Jekyll is done regenerating the site.

I personally use [CodeKit](https://incident57.com/codekit/) and point it to the `_site` folder in my project. It watches for changes on those files and automatically refreshes Chrome. Once incremental regeneration is finished, it will work even better.

> When I am developing, I usually run Jekyll in serve & watch mode with `jekyll serve -w`

@alfredxing I don't remember which version of Jekyll made the change, but the `serve` command enables auto-regeneration by default.
