### ISSUE TITLE
css/main.scss contains syntax errors when I push to gh-pages

### ISSUE THREAD

**Issue by lucachaco** [jekyll/jekyll-help#221]
I keep getting this error but i works fine with i run it with -> bundle exec jekyll serve

This is the file -> https://github.com/lucachaco/sourcequarter-lander/blob/gh-pages/project/website/css/main.scss

It is the same that came with the default theme.

I already tried this workaround but it didnt work -> https://github.com/jekyll/jekyll-help/issues/185

Any help would be appreciate it. 

Thanks.

**Comment by troyswanson** [comment]
I think you could have worked around this by adding a `_config.yml` file in the root of the repo and adding a `source` property that points to the relative position of the root of the Jekyll source... Not entirely sure if that would work though.

Glad you got it working, either way.

**Comment by lucachaco** [comment]
Thank you troyswanson for your comment.
I was going to try that but I saw github overwrites that settings: https://help.github.com/articles/using-jekyll-with-pages/#configuring-jekyll

So, moving the files to the root I think was my only option a the moment.

Thanks.
