### ISSUE TITLE
Can I create a association between two posts (e.g. for multilingual posts)?

### ISSUE THREAD

**Issue by kleinfreund** [jekyll/jekyll-help#222]
I have a bilingual site. For each post, I like to link to its counterpart. Currently, there is no logical connection between the two posts.

The German posts (default) reside in `/_posts` while the English posts are located in `/en/_posts`. The category `en` which is automatically created by having the posts inside `/en` is used for permalinks.

__My question is:__ Is there a way I can _entangle_ two posts (German and English) and create the links to the respective counterpart without writing them directly in my posts? What would be the strategy for that?

_(I let Pages do the build, so plugins won't work. Also, I don't want working code, just a small entry point.)_

**Comment by mattr-** [comment]
There's not really any way to do this currently. It's up to the site creator to determine how they want to handle multilingual sites and how they link their posts together.

**Comment by troyswanson** [comment]
As @mattr- said, there isn't anything built in, but you could create a loop in your posts layout which looks for the translated counterpart and outputs some HTML if it finds something.

Hope this helps.
