### ISSUE TITLE
jekyll vs bundle exec jekyll

### ISSUE THREAD

**Issue by sr-murthy** [jekyll/jekyll-help#225]
Hi

THis is more of a question rather an issue (I am using `bundle exec jekyll <command>` as per the GitHub pages instructions) but what does `bundler` do in relation to `jekyll`, and what is the difference between, say, `jekyll [build | serve]` vs `bundle exec jekyll [build | serve]`?

Right now I am able to build and serve the site locally with `bundle exec jekyll [build | serve]`, but when I `jekyll [build | serve]` it throws the following error

    /Library/Ruby/Gems/2.0.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:4:in `<class:PsychResolver>': uninitialized constant Psych::Nodes (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:2:in `<module:SafeYAML>'
	from /Library/Ruby/Gems/2.0.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:1:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:131:in `<module:SafeYAML>'
	from /Library/Ruby/Gems/2.0.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:26:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll.rb:26:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:6:in `<top (required)>'
	from /usr/bin/jekyll:23:in `load'
	from /usr/bin/jekyll:23:in `<main>'

**Comment by penibelst** [comment]
[Bundler's Purpose and Rationale](http://bundler.io/rationale.html)

**Comment by sr-murthy** [comment]
Thank you, this is very clear :)

**Comment by ghost** [comment]
Thanks for keeping this up! 👍
