### ISSUE TITLE
Jekyll seems to half work

### ISSUE THREAD

**Issue by gitjohndoe** [jekyll/jekyll-help#226]
Repo: https://github.com/gitjohndoe/mediator

Github Page: http://gitjohndoe.github.io/mediator/

Not sure what is wrong here but I have been troubleshooting all day with no results. Can anyone help and tell me what I am doing wrong?

**Comment by rdyar** [comment]
your css is not loading - in your head section try <link rel="stylesheet" type="text/css" media="screen" href="http://gitjohndoe.github.io/mediator/css/main.css">

just /css/main.css isn't working for some reason. On mine I do a relative link line that and it does. I'm guessing you just need the /mediator/ part to make it work.

**Comment by rdyar** [comment]
that goes for any of your other urls to - you need the /mediator/ part. Like your logo.

**Comment by gitjohndoe** [comment]
Yeah so /mediator will do the trick for css, js and images.
Any idea why the posts are not working? 
http://gitjohndoe.github.io/mediator/feature/2014/11/30/mediator_features.html the first post can not be found.

**Comment by rdyar** [comment]
i think because in your _config.yml file you need your base url to include the /mediator .

Which I think you just figured out.

**Comment by gitjohndoe** [comment]
baseurl: "/mediator"
This does fix the css and js but does not fix the posts issue. Still confused here. Really weird.
Thanks for the help by the way

**Comment by rdyar** [comment]
```
url: "http://gitjohndoe.github.io/mediator" # the base hostname & protocol for your site
```
I don't use github, and am not 100% sure on the useage of url vs baseurl. But all your problems stem from the  fact that your site is at /mediator not just github.io. 

i think i would try just using URL and leave Baseurl blank?

**Comment by rdyar** [comment]
the url to the features article is really:
```
http://gitjohndoe.github.io/mediator/mediator/feature/2014/11/30/mediator_features.html
```
the mediator bit is very confusing because it is the name of your repo and the name of the skin you are using. The url above has mediator/mediator/feature because your repo is at /mediator - so it will always be there, then the next mediator is because the Category set for that articel in the frontmatter is 'mediator feature' and jekyll is doing the post url as each word in category is another '/' if that makes sense.

**Comment by gitjohndoe** [comment]
Alright, I will play around with it. At least I know now the posts are being created. Greatly appreciate the help.

**Comment by gitjohndoe** [comment]
http://jekyllrb.com/docs/github-pages/#project-page-url-structure
For others to reference. Again thanks for the help.

**Comment by rdyar** [comment]
no problem, good luck!

I think you need url: "http://gitjohndoe.github.io/mediator"
and baseurl: "/mediator"

but not 100% sure - I think baseurl is for local, url is for what it really is when live.

**Comment by troyswanson** [comment]
Gents, I would highly encourage you to not use `baseurl` and instead use [GitHub Pages Metadata](https://help.github.com/articles/repository-metadata-on-github-pages/).

A quick example: Assuming you have a CSS file called `/css/styles.css` relative to the root of your repo, you can use something like `<link rel="stylesheet" href="{{ site.github.url }}/css/styles.css">`. The `{{ site.github.url }}` value will be replaced by the URL for your repo's site.
