### ISSUE TITLE
Build problem - _config.yml format

### ISSUE THREAD

**Issue by sr-murthy** [jekyll/jekyll-help#228]
Hi

I'm starting my blog site from scratch (I cloned `poole/hyde`) and I'm am trying to test the site locally using `bundle exec jekyll build` (I have added a Gemfile to the root of the source folder).  Now I'm getting the following error:

I am trying to build and test the site locally, using `bundle exec jekyll build`
(I’ve added a Gemfile to the root of the source folder) but I’m now getting
the following error:

    $bundle exec jekyll build --watch
    jekyll 2.4.0 | Error:  (/Users/srm/Documents/sandeep/cst/content/sites/sr-murthy.github.io/_config.yml): did not find expected key while parsing a block mapping at line 3 column 1

The first three lines of `_config.yml` are

    --- 
    # Site setup, content, dependencies and global properties
    title: 'free to code'

Please help.

**Comment by penibelst** [comment]
Remove the first line `---` and try again.

**Comment by sr-murthy** [comment]
Thanks, I had fixed it yesterday.
