### ISSUE TITLE
Leading whitespace is stripped from Markdown highlight block

### ISSUE THREAD

**Issue by kevinushey** [jekyll/jekyll-help#229]
Following from the [lanyon](https://github.com/poole/lanyon) base Jekyll theme, I have Markdown in a file of the form (this being output from `R`):

```
{% highlight text %}
      [,1] [,2]
[1,] FALSE TRUE
[2,] FALSE TRUE
{% endhighlight %}
```

which, after render (through whatever machinery runs in `jekyll serve`), gets generated HTML as:

```
<div class="highlight"><pre><code class="language-text" data-lang="text">[,1]
[1,]    0
[2,]    1
[3,]    2
[4,]    2</code></pre></div>
```

with the leading whitespace in front of `[,1]` removed. 

Is there a way to ensure that leading whitespace is not stripped on render -- perhaps something I can specify in `_config.yml`, or otherwise? FWIW, I have:

```
markdown:            kramdown
highlighter:         pygments
```

in my `_config.yml`, alongside other (obstensibly) unrelated options.

My understanding is that pygments is handling this translation, and [the documentation](http://pygments.org/docs/quickstart/) here suggests that this might (?) be controlled through the `stripall` argument, but I am not sure how I would get access to that (if that is indeed what I need).

Finally -- in the end, my Jekyll website is going to be served through GitHub pages, so the solution would preferably not involve post-processing the generated HTML.

Thanks!

**Comment by troyswanson** [comment]
From the sounds of it, this may be a bug that you want to file in the actual Jekyll repo.

For your particular issue, you might want to try using tables.

 | [,1] | [,2]
--- | --- | ---
**[1,]** | FALSE | TRUE
**[2,]** | FALSE | TRUE

```
 | [,1] | [,2]
--- | --- | ---
**[1,]** | FALSE | TRUE
**[2,]** | FALSE | TRUE
```

**Comment by kevinushey** [comment]
Thanks -- I'll do that, although in general I do want to print generic, verbatim code output without any whitespace stripping.

**Comment by troyswanson** [comment]
Fair enough. Open an issue in the actual Jekyll repo and see if they can look at it.
