### ISSUE TITLE
Why should I use git clone when deploying with git post-receive hook?

### ISSUE THREAD

**Issue by golddranks** [jekyll/jekyll-help#230]
In the deployment guide (http://jekyllrb.com/docs/deployment-methods/), there is the git post-receive hook method explained. I set up my deployment system almost the same way before finding the guide. The only difference is that I don't git clone into a temp directory, like it's done in the guide. Instead I use git reset to write out the HEAD.

Git dir: /srv/git/zuihitsu/zuihitsu.git (a bare repository)
Worktree: /srv/git/zuihitsu/zuihitsu.worktree
Public dir: /srv/www/zuihitsu

I just:

    #!/bin/sh
    git --work-tree=/srv/git/zuihitsu/zuihitsu.worktree reset --hard master
    jekyll build --source /srv/git/zuihitsu/zuihitsu.worktree --destination /srv/www/zuihitsu

That seems to work fine. What are the pros and cons of this reseting method, versus the cloning one? This way git doesn't have the clone the whole repo, just write out this specific branch. But is there any hazards that I'm overlooking?

**Comment by troyswanson** [comment]
@golddranks The goal of the guide was most likely to be as simple as possible and effectively deal with force pushes that modify the history of the repo. If you're doing a hard reset, you're probably fine. I'll leave this issue open for a bit for others to chime in, but I don't see a problem with your method.

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
