### ISSUE TITLE
Robomongo installation troubles

### ISSUE THREAD

**Issue by serun** [jekyll/jekyll-help#231]
Hi,
I just downloaded the file robomongo-0.8.4-x86_64.deb and I installed it on my pc with Ubuntu 12.04.
Everything supposedly went fine, but when I try to use robomongo I get the following message:

/usr/bin/robomongo: riga 16:  8842 Errore di segmentazione (core dump creato) "$ROBO_DIR/robomongo"
 
roughly translatable with:

/usr/bin/robomongo: row 16:  8842 Segmentation error (core dump created) "$ROBO_DIR/robomongo"

can anyone help me?

Thank you.

s.

**Comment by troyswanson** [comment]
Does this have to do with Jekyll at all? Sorry, but we can't be a general
tech support repo...
