### ISSUE TITLE
A file was included in `_layouts/default.html` that is a symlink or does not exist in your `_includes` directory

### ISSUE THREAD

**Issue by russt** [jekyll/jekyll-help#232]
Hi,

Getting an error when I try to deploy to github pages:

A file was included in `_layouts/default.html` that is a symlink or does not exist in your `_includes` directory.

I can't get around this error after many hours.  The source for my site is on github ( https://github.com/russt/russt.github.io ) and the destination is the default ( http://russt.github.io/ ).  I am just generating the default site using "jekyll new" with a few changes to the _config.yaml file.  I have tried both 2.4.0 and 2.5.2 versions of jekyll

Site looks fine locally, so I assume this has to do with how github is generating the site.

Any clues?  I realize that this could be a github issue, but I want to make sure that I'm not missing something basic.

thanks!
-Russ

**Comment by russt** [comment]
okay, this is a good one - I routinely git ignore "foo" files, but in this cas it matched the footer.html pattern.  so indeed the _include file really was missing.

too bad the error message is not more specific about which file is missing!

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
