### ISSUE TITLE
Disqus comments are not showing up

### ISSUE THREAD

**Issue by sr-murthy** [jekyll/jekyll-help#233]
Hi

I'm having problems with the include files for the Disqus comments (and the counter) on my posts.  I've enabled comments in `_config.yml` as follows:

    # Comments
     comments:
       provider: disqus
     disqus: 
       short_name: codefree

My `post.html` layout file, with the two `include` statements at the end, looks like this:
```html
    ---
    layout: default
    ---

    <div class="post">
    <h1 class="post-title">{{ page.title }}</h1>
    <span class="post-date">{{ page.date | date_to_string }}</span>
    {{ content }}
    </div>

    <div class="related">
    <h2>Related Posts</h2>
    <ul class="related-posts">
     {% for post in site.related_posts limit:3 %}
      <li>
        <h3>
          <a href="{{site.url}}{{ post.url }}#disqus_thread">
            {{ post.title }}
            <small>{{ post.date | date_to_string }}</small>
          </a>
        </h3>
      </li>
    {% endfor %}
    </ul>
    </div>
    {% include disqus_comments.html %}
    {% include disqus_comments_counter.html %}
```
These Disqus code in the include files is standard.  I am using the Hyde theme.  I've checked 
What could be going wrong here?  At the moment these are the only two problems I need to fix before adding more content.  Your help would be much appreciated.

Thanks

**Comment by nternetinspired** [comment]
Have you restarted Jekyll? Changes in config.yaml are only picked up on start.

**Comment by nternetinspired** [comment]
Beyond that, perhaps you can include a link to your repo? 

Neither Jekyll nor the Hyde theme include Disqus comments, so you are not really giving us much to work on ;)

**Comment by sr-murthy** [comment]
Hi

Sorry about the info., I tried again and it worked.  I think it was the `disqus.short_name` field that I didn't set the correct value for, but it does work now.  Here's the link to the Disqus thread for one of my posts

https://sr-murthy.github.io/os/x,/shells/2015/01/08/Bashed/#disqus_thread

Thanks.

P. S. THe

**Comment by nternetinspired** [comment]
:cool: 

Thanks for confirming.
