### ISSUE TITLE
Help... with errors

### ISSUE THREAD

**Issue by luckyluke007** [jekyll/jekyll-help#234]
Tried build the site, and I got this errors..

WARN: Unresolved specs during Gem::Specification.reset:
      redcarpet (~> 3.1)
      jekyll-watch (~> 1.1)
      classifier-reborn (~> 2.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Users/name.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/bin/jekyll:21:in `block in <top (required)>': cannot load such file -- jekyll/version (LoadError)
	from /Users/name.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:18:in `program'
	from /Users/name/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /Users/name/.rbenv/versions/2.1.2/bin/jekyll:23:in `load'
	from /Users/name/.rbenv/versions/2.1.2/bin/jekyll:23:in `<main>'

**Comment by budparr** [comment]
Not entirely sure, but maybe run ```bundle update``` and see if that helps.

**Comment by luckyluke007** [comment]
Ran the update, It started up and build fine, but still get this warning. 

WARN: Unresolved specs during Gem::Specification.reset:
      redcarpet (~> 3.1)
      jekyll-watch (~> 1.1)
      classifier-reborn (~> 2.0)

Ran bundle exec jekyll serve to eliminate the WARN..

Server address is change to 127.0.0.1 instead 0.0.0.0: 4000.. Would VPN set up change the server address?

Thanks...

**Comment by budparr** [comment]
wonder if you have ```github-pages``` in your gemfile. I see you have the latest Jekyll, but but Github Pages is still on 2.4 https://pages.github.com/versions/

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
