### ISSUE TITLE
I'm trying to migrate my Ghost's post to Jekyll format but getting error

### ISSUE THREAD

**Issue by jitendravyas** [jekyll/jekyll-help#235]
I have posted here http://stackoverflow.com/questions/27815264/how-to-extract-blog-posts-from-ghost-and-import-in-github-hosted-jekyll

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
