### ISSUE TITLE
Jekyll (Kramdown) removes closing PRE tag

### ISSUE THREAD

**Issue by uliwitness** [jekyll/jekyll-help#236]
I have this post:

	---
	layout: post
	status: publish
	published: true
	title: Handling keypresses in Cocoa games
	author:
	  display_name: uliwitness
	  login: uliwitness
	  email: xxx@example.com
	  url: ''
	author_login: uliwitness
	author_email: xxx@example.com
	wordpress_id: 736
	wordpress_url: http://orangejuiceliberationfront.com/?p=736
	date: '2014-12-13 11:57:08 +0100'
	date_gmt: '2014-12-13 11:57:08 +0100'
	categories:
	- Macintosh
	- Objective-C
	- Programming
	- Game Design
	tags: []
	comments: []
	---
	<p>The solution is to keep track of which key is down yourself. Override <tt>-keyDown</tt> and <tt>-keyUp</tt> to keep track of which keys are being held down. I'm using a C++ <tt>unordered_set</tt> for that, but an Objective-C <tt>NSIndexSet</tt> would work just as well:</p>
	<pre>
	@interface ICGMapView : NSView
	{
		std::unordered_set<unichar>	pressedKeys;
	}
	
	@end
	</pre>
	<p>and in the implementation:</p>
	<pre>
	-(void)	keyDown:(NSEvent *)theEvent
	{
		NSString	*	pressedKeyString = theEvent.charactersIgnoringModifiers;
		unichar			pressedKey = (pressedKeyString.length > 0) ? [pressedKeyString characterAtIndex: 0] : 0;
		if( pressedKey )
			pressedKeys.insert( pressedKey );
	}
	
	
	-(void)	keyUp:(NSEvent *)theEvent
	{
		NSString	*	pressedKeyString = theEvent.charactersIgnoringModifiers;
		unichar			pressedKey = (pressedKeyString.length > 0) ? [pressedKeyString characterAtIndex: 0] : 0;
		if( pressedKey )
		{
			auto foundKey = pressedKeys.find( pressedKey );
			if( foundKey != pressedKeys.end() )
				pressedKeys.erase(foundKey);
		}
	}
	</pre>

And when I `jekyll build` this file, it removes the first closing PRE tag (after "@end"):

	<!DOCTYPE html>
	<html>
	
	  <head>
	  <meta charset="utf-8">
	  <meta http-equiv="X-UA-Compatible" content="IE=edge">
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	
	  <title>Handling keypresses in Cocoa games</title>
	  <meta name="description" content="The solution is to keep track of which key is down yourself. Override -keyDown and -keyUp to keep track of which keys are being held down. I'm using a C++ un...">
	
	  <link rel="stylesheet" href="/css/main.css">
	  <link rel="canonical" href="http://orangejuiceliberationfront.com/macintosh/objective-c/programming/game%20design/2014/12/13/handling-keypresses-in-cocoa-games.html">
	  <link rel="alternate" type="application/rss+xml" title="Orange Juice Liberation Front" href="http://orangejuiceliberationfront.com/feed.xml" />
	</head>
	
	
	  <body>
	
		<header class="site-header">
	
	  <div class="wrapper">
	
		<a class="site-title" href="/">Orange Juice Liberation Front</a>
	
		<nav class="site-nav">
		  <a href="#" class="menu-icon">
			<svg viewBox="0 0 18 15">
			  <path fill="#424242" d="M18,1.484c0,0.82-0.665,1.484-1.484,1.484H1.484C0.665,2.969,0,2.304,0,1.484l0,0C0,0.665,0.665,0,1.484,0 h15.031C17.335,0,18,0.665,18,1.484L18,1.484z"/>
			  <path fill="#424242" d="M18,7.516C18,8.335,17.335,9,16.516,9H1.484C0.665,9,0,8.335,0,7.516l0,0c0-0.82,0.665-1.484,1.484-1.484 h15.031C17.335,6.031,18,6.696,18,7.516L18,7.516z"/>
			  <path fill="#424242" d="M18,13.516C18,14.335,17.335,15,16.516,15H1.484C0.665,15,0,14.335,0,13.516l0,0 c0-0.82,0.665-1.484,1.484-1.484h15.031C17.335,12.031,18,12.696,18,13.516L18,13.516z"/>
			</svg>
		  </a>
	
		  <div class="trigger">
			
		  </div>
		</nav>
	
	  </div>
	
	</header>
	
	
		<div class="page-content">
		  <div class="wrapper">
			<div class="post">
	
	  <header class="post-header">
		<h1 class="post-title">Handling keypresses in Cocoa games</h1>
		<p class="post-meta">Dec 13, 2014 • {"display_name"=>"uliwitness", "login"=>"uliwitness", "email"=>"witness.of.teachtext@gmx.net", "url"=>""}</p>
	  </header>
	
	  <article class="post-content">
		<p>The solution is to keep track of which key is down yourself. Override <tt>-keyDown</tt> and <tt>-keyUp</tt> to keep track of which keys are being held down. I'm using a C++ <tt>unordered_set</tt> for that, but an Objective-C <tt>NSIndexSet</tt> would work just as well:</p>
	<pre>
	@interface ICGMapView : NSView
	{
		std::unordered_set<unichar>	pressedKeys;
	}
	
	@end
	
	<p>and in the implementation:</p>
	<pre>
	-(void)	keyDown:(NSEvent *)theEvent
	{
		NSString	*	pressedKeyString = theEvent.charactersIgnoringModifiers;
		unichar			pressedKey = (pressedKeyString.length &gt; 0) ? [pressedKeyString characterAtIndex: 0] : 0;
		if( pressedKey )
			pressedKeys.insert( pressedKey );
	}
	
	
	-(void)	keyUp:(NSEvent *)theEvent
	{
		NSString	*	pressedKeyString = theEvent.charactersIgnoringModifiers;
		unichar			pressedKey = (pressedKeyString.length &gt; 0) ? [pressedKeyString characterAtIndex: 0] : 0;
		if( pressedKey )
		{
			auto foundKey = pressedKeys.find( pressedKey );
			if( foundKey != pressedKeys.end() )
				pressedKeys.erase(foundKey);
		}
	}
	</pre>
	</unichar></pre>
	
	  </article>
	
	</div>
	
		  </div>
		</div>
	
		<footer class="site-footer">
	
	  <div class="wrapper">
	
		<h2 class="footer-heading">Orange Juice Liberation Front</h2>
	
		<div class="footer-col-wrapper">
		  <div class="footer-col  footer-col-1">
			<ul class="contact-list">
			  <li>Orange Juice Liberation Front</li>
			  <li><a href="mailto:"></a></li>
			</ul>
		  </div>
	
		  <div class="footer-col  footer-col-2">
			<ul class="social-media-list">
			  
	
			  
			  <li>
				<a href="https://twitter.com/uliwitness">
				  <span class="icon  icon--twitter">
					<svg viewBox="0 0 16 16">
					  <path fill="#828282" d="M15.969,3.058c-0.586,0.26-1.217,0.436-1.878,0.515c0.675-0.405,1.194-1.045,1.438-1.809
					  c-0.632,0.375-1.332,0.647-2.076,0.793c-0.596-0.636-1.446-1.033-2.387-1.033c-1.806,0-3.27,1.464-3.27,3.27 c0,0.256,0.029,0.506,0.085,0.745C5.163,5.404,2.753,4.102,1.14,2.124C0.859,2.607,0.698,3.168,0.698,3.767 c0,1.134,0.577,2.135,1.455,2.722C1.616,6.472,1.112,6.325,0.671,6.08c0,0.014,0,0.027,0,0.041c0,1.584,1.127,2.906,2.623,3.206 C3.02,9.402,2.731,9.442,2.433,9.442c-0.211,0-0.416-0.021-0.615-0.059c0.416,1.299,1.624,2.245,3.055,2.271 c-1.119,0.877-2.529,1.4-4.061,1.4c-0.264,0-0.524-0.015-0.78-0.046c1.447,0.928,3.166,1.469,5.013,1.469 c6.015,0,9.304-4.983,9.304-9.304c0-0.142-0.003-0.283-0.009-0.423C14.976,4.29,15.531,3.714,15.969,3.058z"/>
					</svg>
				  </span>
	
				  <span class="username">uliwitness</span>
				</a>
			  </li>
			  
			</ul>
		  </div>
	
		  <div class="footer-col  footer-col-3">
			<p class="text"></p>
		  </div>
		</div>
	
	  </div>
	
	</footer>
	
	
	  </body>
	
	</html>

Let me know if you need more info or the original files.

NB -- there were oodles of empty lines in the trigger div which I deleted for this report. The original post was generated by `jekyll-import` from a WordPress post, for which I can also provide the original if needed.

**Comment by uliwitness** [comment]
Nevermind, found the issue: It's the "<unichar>" in the example code. Changing that to &lt;unichar&gt; on the Wordpress server fixed the removal of the Pre tag.

**Comment by troyswanson** [comment]
Hey @uliwitness, I would highly encourage you to use code highlighting in your Markdown files instead of including straight HTML in them.

You'd be able to get away with much more from an input perspective, plus your code would render with fancy colors!

**Comment by uliwitness** [comment]
This is a WordPress import, so I might eventually do that, but right now I just want to migrate the blog intact :-)
