### ISSUE TITLE
Assigning multiple collections to a filtered loop variable

### ISSUE THREAD

**Issue by graemeduckett** [jekyll/jekyll-help#238]
I have a couple collections set up, 'case-studies' and 'projects', and I have front matter variables within them for things like client name, project date, project name, etc. I have successfully created loops that display only projects from a specific client, sorted by date, for example, but would I would like to do is create a loop that displays both case studies and projects from a specific client, sorted by date. I'm curious if there is a way to assign more than one collection to a variable to be passed to the loop? Something like the following:

<pre>{% assign client_timeline = site.projects and site.case-studies | where: 'client', page.client | sort: 'date' %}

{% for timeline_item in client_timeline %}
{% endfor %}</pre>

Everything here has proven successful except for the second collection, which is ignored.

Assigning filtered variables to loops seems like a pretty powerful feature, but I haven't found a lot of documentation on what all can be done with them. I've just started with Jekyll last week so any resources with advanced usage documentation would be greatly appreciated!

**Comment by troyswanson** [comment]
You're getting into some pretty advanced Jekyll stuff pretty quick! Bravo.

I think this (lack of) behavior is being blocked by https://github.com/Shopify/liquid/issues/427.

**Comment by graemeduckett** [comment]
Thanks for your reply. That is disheartening news! I was feeling so close. I see there hasn't been much action on the topic since August but here's hoping it gets implemented.

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
