### ISSUE TITLE
condition.rb:18:in `block in <class:Condition>': undefined method `include?' for ??? (NoMethodError)

### ISSUE THREAD

**Issue by deragon** [jekyll/jekyll-help#240]
Liquid Exception: undefined method `include?' for 1111884:Fixnum in _layouts/bug.html
/var/lib/gems/1.9.1/gems/liquid-2.6.1/lib/liquid/condition.rb:18:in `block in <class:Condition>': undefined method `include?' for 1111884:Fixnum (NoMethodError)

Beginner to Ruby and Jekyll here.  Not sure if this is a real bug of my fault.  Maybe a dependency is missing?  I have a layout (bug.html) that uses the Liquid "contains" operator and it fails there.  If I use any other operator, i.e. == or != for instance, it works fine.

If a dependency is missing, Jekyll should complain about it instead of launching.  Jekyll 2.5.3 used.  Version of Gems and Liquid are 1.9.1 and 2.6.1 respectively, according to the path given in the error message.  I use Ubuntu 14.04 LTS Trusty Thar.

**Comment by kansaichris** [comment]
Could you paste the content of your layout (`bug.html`)?

**Comment by deragon** [comment]
Sorry for the late reply, your question found its self in gmail's spam box.  Here is the content.

    ---
    layout: default
    ---
    <div class="post">

      <header class="post-header">
        <p class="post-meta">{{ page.date | date: "%b %-d, %Y" }}{% if page.author %} • {{ page.author }}{% endif %}{% if page.meta %} • {{ page.meta }}{% endif %}</p>

        <table class="bug-table">
          {% for data in page.bug %}
          <tr class="bug-table">
            <td>
              {{ data[0] }}
            </td>
            <td>
              {% if data[1] != nil %}
                {% if data[1] contains "http" %}
                  Bonjourldskf
                {% endif %}
              {% endif %}
              {{ data[1] }}
            </td>
          </tr>
          {% endfor %}

          <tr class="bug-table">
            <td>
            Manual Title
            </td>
            <td>
            {{ page.bug.title }}
            </td>
              {% if data[1] contains 'http' %}
              a href="{{ data[1] }}"
              {% endif %}
          </tr>
          <tr class="bug-table">
            <td>
              Number
            </td>
            <td>
              {{ page.bug.number }}
            </td>
          </tr>
        </table>

        <p class="bug-meta">{{ page.launchpad }} </p>
        <p class="bug-meta">{{ page.upstream}} </p>
        <p class="bug-meta">page.bug.title = {{ page.bug.title }} </p>
        <p class="bug-meta">page.bug.number = {{ page.bug.number }} </p>
        <p class="bug-meta">{{ page.bug.system }} </p>
        <p class="bug-meta">{{ page.bug.component }} </p>
        <p class="bug-meta">{{ page.bug.launchpad }} </p>
        <p class="bug-meta">{{ page.bug.upstream }} </p>

      </header>

      <article class="post-content">
        {{ content }}
      </article>

    </div>

**Comment by gkv311** [comment]
I have the same problem when tried to use date in the post title and them filter them in the following way:
{% if post.title contains '2014-10-12' %}

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
