### ISSUE TITLE
How can I allow people to read my Jekyll site offline?

### ISSUE THREAD

**Issue by tomjohnson1492** [jekyll/jekyll-help#241]
To avoid having to give offline readers a PDF, I want to simply deliver the _site files to readers. They would simply open the index.html file and load the content in a browser. However, right now it doesn't work. I have this in my _config.yml file:

```
baseurl: "/acme"
```

What would I need to change in the baseurl or elsewhere in order for people to be able to simply open index.html from _site without having jekyll installed and be able to view the site?

**Comment by kleinfreund** [comment]
You need to make sure, that all your links (everything inside `href=""` and `src=""`) are __relative to the file__. That means they must never start with a `/` or a protocol `http://`, etc. You need to reference ressources like this: `src="../img/image.pnG"`. Than, if your site is static, it should work out of the box.

**Comment by tomjohnson1492** [comment]
Great. Thanks!

**Comment by kleinfreund** [comment]
Of course if another file is in the same directory, you just need `href="about.html"`, etc.

**Comment by tomjohnson1492** [comment]
for me the trick will be figuring out how to create a toggle in my config file that says whether to create an offline site or not. the main audience will read the content online, but a small percentage will need it offline. if online, then the baseurl needs to be appended; if offline, it doesn't -- that kind of thing.

**Comment by kleinfreund** [comment]
The tradeoff with what I suggested above is maintainability. Writing out links relatively to files is a _harder_ task than using the root (with `/`). However, the above works both online and offline. That's the whole point of it.

**Comment by tomjohnson1492** [comment]
I'm still having trouble getting this to work. I installed a vanilla jekyll site. I added a page called cats.html. On my index page, I linked to it like this: `<a href="/cats.html">cats</a>`. The link works fine. However, if I launch the index file in the _site root directory, instead of using the server mode, I see this: http://www.screencast.com/t/eCD9yNjyP

I tried commenting out baseurl and url in the _config.yml file, but I still get the same result when I launch the index.html file.

I know it may seem an odd request, but basically I'm using Jekyll for documentation. Sometimes people request PDFs due to lack of access to the site. I want to send them a zip file containing the static site, and tell them to just click index.html to open it. 

What am I doing wrong here? Thanks,

Tom

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
