### ISSUE TITLE
Jekyll's installation process shenanigans.

### ISSUE THREAD

**Issue by Ysag** [jekyll/jekyll-help#245]
Greetings fellas,

Been struggilng with the installation process for windows(i can't afford a mac), following some very precise tutorials i got myself around installing ruby and a devkit(both are compatible with each other).

But when i try to run the jekyll cmd on the console(not windows's) i get an error message as if there was an error while fetching data from jekyll's server.

Any thought/recommendations are welcome, thanks for your time in advance and have a great day!.

- Ysag

**Comment by kleinfreund** [comment]
That error message you were talking about, where is it? That'd be super helpful to help you out.

**Comment by Ysag** [comment]
ERROR: Could not find a valid gem 'jekyll' <>=0>, here is why:
	Unable to download data from https://rubygems.org/ - SSL_connect returned=1
	errno=0 state=SSLv3 read server certificate B: certificate verify failed <https://api.rubygems.org/latest_specs.4.8.gz>

Here's the exact same message i am getting. Thanks for your help btw.

**Comment by troyswanson** [comment]
Check out this [SO answer](http://stackoverflow.com/a/27641786).

**Comment by Ysag** [comment]
Thanks for the info Travis!. Though it tells me to run the setup.rb, I assumed to run it with ruby but it is not picking it up. Do i have to have these files on the same dir as for ruby?.

**Comment by troyswanson** [comment]
I don't know 100% but I wouldn't expect so. You should just be able to unzip the file into some folder somewhere, and then run `ruby setup.rb` while you're in that folder.

PS: I'm Troy. :smile:

**Comment by Ysag** [comment]
Sorry for that namechange all of a sudden!. The thing is that it's not letting me run it, it's not picking the file type(extension) and i tried going to the folder and running it but it won't. 

Sorry for taking all of your time people!, but i just of now got started with ruby and jekyll. I've only used ST for offline Front-end designing.

-Ysag

**Comment by troyswanson** [comment]
Oh, try being inside a `cmd` window, `cd` into that folder, and try running
`ruby setup.rb` there.

**Comment by troyswanson** [comment]
Oh, try being inside a `cmd` window, `cd` into that folder, and try running `ruby setup.rb` there.

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
