### ISSUE TITLE
Paths to other pages versus paths to images seems inconsistent

### ISSUE THREAD

**Issue by tomjohnson1492** [jekyll/jekyll-help#246]
I'm a little confused on subdirectory paths with with links to pages versus links to images. In my root directory, I have a folder called "content." In "content" I have a subdirectory called "web". If I want to link to a page in content/web, I just reference the permalink, like this: 

```
[Tutorial]({{ "/tutorial" | prepend: site.baseurl }})
```
In my root directory, I have another folder called "images." Inside images, I have a subdirectory called web. If I have an image in there and want to link to it, I would use this:

```
![Sample Wiki Image]({{ "/images/web/samplewiki.png" | prepend: site.baseurl }})
```

It seems that with pages, which have a permalink attribute in the front matter, I don't need to specify the path to the page -- I just reference the page's permalink. 

But with images, it's not the case. Images require me to use the subdirectory path. 

Is this correct?

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
