### ISSUE TITLE
How can I limit results to one match when two conditions match?

### ISSUE THREAD

**Issue by tomjohnson1492** [jekyll/jekyll-help#247]
I want to cycle through my pages and get all pages that have either a tag called "release_notes" or a tag called "news." Here's my code:

```
{% for page in site.pages limit: 5 %}
{% for tag in page.tags %}
{% if tag == "release_notes" or tag == "news" %}
<li><a href="{{ page.permalink | prepend: site.baseurl }}">{{page.title}}</a></li>
<div class="summary">{{page.summary}}</div>
{% endif %}
{% endfor %}
{% endfor %}
```

One of my pages has front matter as follows:

```
---
layout: page
title: 2.0 Release Notes
permalink: /release_notes_2_0/
tags: 
- release_notes
- news
---
```

This page appears twice in the `for` loop. How can I make it so that the page only appears once? 

(I realize the simple solution would be to restrict the tags to one per page, or restrict the for loop to one tag per loop, but maybe it's easier to do this than I thought.)

**Comment by albertogg** [comment]
Hello @tomjohnson1492, could you try something like:

```ruby
    {% assign pages = site.pages limit:5 %}
    {% for p in pages  %}{% unless p.tags == release_notes || news %}
      <li><a href="{{ page.permalink | prepend: site.baseurl }}">{{page.title}}</a></li>
      <div class="summary">{{page.summary}}</div>
    {% endunless %}{% endfor %}
```

and see if it works? I'm not sure, tho.

**Comment by tomjohnson1492** [comment]
Thanks for responding. I tried your suggestion but it didn't work. I got a long list of bullet items, without any content (text) with each bullet.

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
