### ISSUE TITLE
Re-usability of posts (and include of external posts) ?

### ISSUE THREAD

**Issue by emmairwin** [jekyll/jekyll-help#249]
Hi, 

So one of the things I would like to have is  a way to make a '_posts' available to other modules without duplication.  But also 'import' posts.  For context, we're building education & training modules, where 'posts' are training components relating to the module.  We have more than one instance of Jeykll and want to 'share content'.

Currently: 
1) One post called 'conflict resolution' in training module 1, is also used by two other modules, and so it must be copied to each of those modlues.
2) If content for that post needs to be  updated, I have to copy it across all three instances.
3) if someone wants to contribute a change to that post ,   they have to submit a PR to all 3, or I have to copy their PR to all three.
4) Additionally, we are running more than one instance of Jeykll and may want to share a post, so would like to 'include' an external post ie : https://raw.githubusercontent.com/emmairwin/reps-edu-cirriculum/master/modules/conflict_resolution.markdown    vrs make yet another (now external) copy.

So this is about modularity  and maintainability of content, but to encourage quality of content through participation (contribution). I know that's not a 'blog thing', but it is a community thing, and a way that invites contribution and re-use for community projects.  

I'm new to Ruby(but long-time web-dev), so have been playing with this but not quite sure what's possible. I'm sure there are holes in what I am proposing - but I really need a more modular/reusable way of working with posts. I am playing with the code, but if there are suggestions that would be helpful

**Comment by emmairwin** [comment]
I've since found I can include a GIST, which is kind of sort of the right path:  ie  {% gist emmairwin/09e8c365b7dc1c3c0d35 %} , I just it to render as markup.

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
