### ISSUE TITLE
How to create simple custom note tag?

### ISSUE THREAD

**Issue by tomjohnson1492** [jekyll/jekyll-help#251]
I want to create a custom liquid tag that allows me to easily wrap a note in a specific class. 

For example, currently to create a note, I write this:

```
<div class="alert alert-info" role="alert">This is a note. </div>
```

I want to create a custom liquid tag that allows me to simply write this:

```
{% alert This is a note.%}
```

I looked at the [Jekyll docs](http://jekyllrb.com/docs/plugins/#available_plugins) for creating a custom liquid tags via plugins, and found this sample:

```ruby
module Jekyll
  class RenderTimeTag < Liquid::Tag

    def initialize(tag_name, text, tokens)
      super
      @text = text
    end

    def render(context)
      "#{@text} #{Time.now}"
    end
  end
end

Liquid::Template.register_tag('render_time', Jekyll::RenderTimeTag)
```

I saved this code as a file and added it to my _plugins directory -- and it worked. So I tried to clone the code and modify it as follows:

```
module Jekyll
  class RenderNoteTag < Liquid::Tag

    def initialize(tag_name, text, tokens)
      super
      @text = text
    end

    def render(context)
      "#{@text} <div class='alert alert-info' role='alert'>my alert</div>"
    end
  end
end

Liquid::Template.register_tag('render_note', Jekyll::RenderNoteTag)
```

I then inserted it on a page using this:

```liquid
{% render_note %}
```

It works, but how do I add my note in the liquid tags? I want to add something like this:

```liquid
{% render_note this is my note %}
```

And have "this is my note" wrapped inside like this:

```html
<div class="alert alert-info" role="alert">This is a note. </div>
```

**Comment by pootsbook** [comment]
I believe you were almost there. This is worked for me (`jekyll 2.5.3`):

```ruby
# _plugins/render_note.rb
module Jekyll
  class RenderNoteTag < Liquid::Tag

    def initialize(tag_name, text, tokens)
      super
      @text = text
    end

    def render(context)
      "<div class=\"alert alert-info\" role=\"alert\">#{@text}</div>"
    end
  end
end

Liquid::Template.register_tag('render_note', Jekyll::RenderNoteTag)
```

```liquid
{% render_note This is a note. %}
```
resulted in:
```html
<div class="alert alert-info" role="alert">This is a note. </div>
```

Let me know how you get on.

**Comment by tomjohnson1492** [comment]
Thanks for the help. However, the code you suggested didn't work. It doesn't render any surrounding div tags at all. I just get `<p>This is a note</p>`. 

I'm not familiar with the liquid syntax here, so I'm not sure where `#{@text}` must appear. Is this ruby, or is it specific to Liquid?

**Comment by pootsbook** [comment]
The syntax is Ruby String interpolation, e.g.

```ruby
@text = "example"
puts "This is an #{@text}"
#=> "This is an example"
```
Note, that for the variable to be interpolated, the interpolation `#{}` must occur within a double quoted string.

Can you paste your code in so I can have a look for you?

**Comment by tomjohnson1492** [comment]
Hey, it's working now. I didn't restart the server earlier. When I restarted it, it's all working. (The code is the same as what you pasted above.) Thanks so much for your help. This technique is going to be tremendously helpful.

**Comment by pootsbook** [comment]
Great :+1:
