### ISSUE TITLE
How to write a new data generation feature + test

### ISSUE THREAD

**Issue by grobmeier** [jekyll/jekyll-help#252]
Hi,

I need to use a mongodb like it would be a json data file and plan to write a new feature for it.
However I didn't find the place where the _data readers are implemented.

Can you give a brief oversight about what would needed to be done to create such a feature and how it would be properly tested (speaking of server dependency) so it would be accepted in the jekyll project?

Thanks!

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
