### ISSUE TITLE
`:title` in collections seems to parse punctuation differently

### ISSUE THREAD

**Issue by beep** [jekyll/jekyll-help#253]
I use a collection to manage “draft” entries, so I can print out a schedule of upcoming entries on my site. But when generating output files from that collection, it seems `:title` might be parsed differently in collections than it is elsewhere?

Here’s what I’m working from:

- Post’s filename: `_collection/2015-01-26-laphams-quarterly.markdown`
- Post’s title, in the front matter: `Lapham’s Quarterly”
- Permalink definition for the collection: `dir/:title:output_ext`
- Default permalink setting: `dir/:title:output_ext`

When served, this results in:

- `dir/lapham-s-quarterly.html` if the post is in the collection; and
- `dir/laphams-quarterly.html` if the post is in `_posts`.

(I am very likely doing something horribly wrong, but thought I’d log it here in case the issue’s relevant to anyone else.)

**Comment by paulrobertlloyd** [comment]
I suspect this may be fixed when posts become a type of collection… looks like there are some under-the-hood differences in how URL slugs are handled for each type… but that’s just a guess. Am I right @parkr?

By the way @beep, have you seen the built in handling for draft posts: http://jekyllrb.com/docs/drafts/ ?

**Comment by beep** [comment]
@paulrobertlloyd I have, thanks! (I opted for a collection because we _do_ want to output files from the “drafts” collection, and to print out a list of the upcoming entries; near as I could tell, those things aren’t possible with `_drafts`.)

**Comment by parkr** [comment]
Hey, @beep! Sorry you ran into this problemo. Turns out we [extract the slug (used by `:title`) from the post filename](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/post.rb#L170), whereas collection documents' slugs [are generated either from the `title` element in the YAML front matter or, if it doesn't exist, by the file basename](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/document.rb#L135).

It would make sense to me to call the slug the input file's basename in all cases (with date data stripped, of course). What say you?

**Comment by beep** [comment]
> It would make sense to me to call the slug the input file's basename in all cases (with date data stripped, of course). What say you?

@parkr That’d be what I expect, and gets a big +1 from me! Thanks!

(And thanks for weighing in!)

**Comment by parkr** [comment]
Terrific! Would you mind filing a bug for this in jekyll/jekyll? We'll get it fixed as soon as we can. :)

**Comment by beep** [comment]
@parkr Done and done—please let me know if [the bug](https://github.com/jekyll/jekyll/issues/3372) should be worded differently. And thank you so much for weighing in!

**Comment by parkr** [comment]
Tracking over in jekyll/jekyll. Thanks, all!
