### ISSUE TITLE
How can I modify slugify utility so that I can use underscores in URLs, not hyphens.

### ISSUE THREAD

**Issue by paulrobertlloyd** [jekyll/jekyll-help#254]
I’m moving my old site (with legacy URLs) over to Jekyll, and that site generated URLs with underscores (which I actually prefer). I've subclassed slugify (`Jekyll::Utils`) to achieve this on my new Jekyll-powered site, but I'd like to release this as a plugin with a configurable value. This is what I’ve got so far:

```ruby
module Jekyll

  class SlugifyCharacterGenerator < Jekyll::Generator
    def generate(site)
      @site = site
      @slugify_character = @site.config['slugify_character']

      if @slugify_character.nil?
        @slugify_character = '-'
      else
        @slugify_character = @slugify_character
      end
    end
  end

  module Utils
    # Slugify a filename or title.
    #
    # string - the filename or title to slugify
    # mode - how string is slugified
    #
    # When mode is "none", return the given string in lowercase.
    #
    # When mode is "raw", return the given string in lowercase,
    # with every sequence of spaces characters replaced with a hyphen.
    #
    # When mode is "default" or nil, non-alphabetic characters are
    # replaced with a hyphen too.
    #
    # When mode is "pretty", some non-alphabetic characters (._~!$&'()+,;=@)
    # are not replaced with hyphen.
    #
    # Examples:
    #   slugify("The _config.yml file")
    #   # => "the-config-yml-file"
    #
    #   slugify("The _config.yml file", "pretty")
    #   # => "the-_config.yml-file"
    #
    # Returns the slugified string.
    def slugify(string, mode=nil)
      mode ||= 'default'
      return nil if string.nil?
      return string.downcase unless SLUGIFY_MODES.include?(mode)

      # Replace each character sequence with a hyphen
      re = case mode
      when 'raw'
        SLUGIFY_RAW_REGEXP
      when 'default'
        SLUGIFY_DEFAULT_REGEXP
      when 'pretty'
        # "._~!$&'()+,;=@" is human readable (not URI-escaped) in URL
        # and is allowed in both extN and NTFS.
        SLUGIFY_PRETTY_REGEXP
      end

      string.
        # Strip according to the mode
        gsub(re, @slugify_character).
        # Remove leading/trailing hyphen
        gsub(/^\-|\-$/i, '').
        # Downcase
        downcase
    end

  end
end
```

@slugify_character isn't output when placed inside the subclassed slugify. I am a total Ruby n00b — how can I make this work? Secondly, do I need to replicate the entirety of this class, or is there a simpler means of achieving the same… I bet there is!

**Comment by troyswanson** [comment]
I don't know Ruby very well myself, but hopefully someone will be able to help out.

However, I would be remiss if I didn't point out that you really should use hyphens instead of underscores in your URL, though. Google specifically recommends this in a [support article](https://support.google.com/webmasters/answer/76329?hl=en):

> We recommend that you use hyphens (-) instead of underscores (_) in your URLs.

**Comment by paulrobertlloyd** [comment]
Google recommending it is actually one of the reasons I prefer to use underscores ;-)

**Comment by kleinfreund** [comment]
> Google recommending hyphens is actually one of the reasons I prefer to use underscores ;-)

Why?

**Comment by paulrobertlloyd** [comment]
@kleinfreund:

> Make pages primarily for users, not for search engines.
— https://support.google.com/webmasters/answer/35769?hl=en

**Comment by troyswanson** [comment]
@paulrobertlloyd @kleinfreund :disappointed: Let's not get into this here, please.

If anyone wants to help out with @paulrobertlloyd's plugin, feel free to chime in.

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
