### ISSUE TITLE
Simple way to do case-insensitive sort?

### ISSUE THREAD

**Issue by egardner** [jekyll/jekyll-help#255]
Hello-

I'm trying to figure out if there is a straightforward way to sort a list of tags in **case-insensitive** order.

Right now my tags post looks like this:

```
<ul>
  {% assign sorted_tags = site.tags | sort %}
  {% for tag in sorted_tags %}
    <h4 id="{{tag[0]}}" class="meta">{{tag[0] | upcase}}</h4>
    <br>
    {% for tagged_post in tag[1] %}
      <a href="{{site.baseurl}}{{tagged_post.url}}">{{tagged_post.title}}</a>
      <br>
    {% endfor %}
    <hr>
  {% endfor %}
</ul>
```

This returns the capitalized Tag names first, followed by lowercase names, in alphabetical order. I'd rather just upcase/downcase everything before sorting so the capitalization of the tag name doesn't matter.

Is this a place to use the `map` filter? There is not very much documentation on how to use this on either the Jekyll or Shopify docs, so I'm sort of at a loss there.

Thanks for reading!

Edit: the repo in question is [here](https://github.com/gettypubs/beyond-the-printed-page) for reference.

**Comment by tkrotoff** [comment]
I have the same problem. I've opened an issue at https://github.com/Shopify/liquid/issues/529 asking for adding case-insensitive sort.

**Comment by tkrotoff** [comment]
@egardner I've created a filter sort_casecmp that does what you want: https://github.com/tkrotoff/osteo15.com/commit/c7a25082b5d4c83c4d6c75db3ede3395c0277b80

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
