### ISSUE TITLE
Get frontmatter of specific post

### ISSUE THREAD

**Issue by kaatt** [jekyll/jekyll-help#256]
```
_posts
-- 2015-01-20-foo.md
-- 2015-01-20-bar.md
```
2015-01-20-foo.md:
```
---
title: Foo
img: 12345
---
```
Is there a way to get the `img` front matter for just `foo.md` in any other jekyll file?

Like `site.posts[2015-01-20-foo].img`?

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
