### ISSUE TITLE
Do folders that hold pages really need index.html files? 

### ISSUE THREAD

**Issue by tomjohnson1492** [jekyll/jekyll-help#259]
I saw this in the Jekyll docs [here](http://jekyllrb.com/docs/pages/):

>Where you put HTML files for pages depends on how you want the pages to work. There are two main ways of creating pages:
>Place named HTML files for each page in your site’s root folder.
Create a folder in the site’s root for each page, and place an index.html file in each page folder.

I have a folder in my directory called "content." This directory includes lots of pages, but there is no index.html. The pages render just fine. Is this documentation outdated?

**Comment by tomjohnson1492** [comment]
Also, the section that follows ([Named folders containing index HTML files](http://jekyllrb.com/docs/pages/#named-folders-containing-index-html-files))  talks about "clean" pages. I think this section is outdated as well. I'm not implementing the technique, and my pages aren't muddled with file extensions.

**Comment by kleinfreund** [comment]
There is a difference whether you have `/blablabla/mrfreeman.html` or `/blablabla/mrfreeman/index.html`. The last one can be accessed by navigating to `/blablabla/mrfreeman`, wheras the first needs the extension.

**Comment by tomjohnson1492** [comment]
I have the former setup (sans index.html) and I can access by navigating to `/blablabla/mrfreeman`.

**Comment by kleinfreund** [comment]
Are you hosting on GitHub Pages or on something else? One can achieve extension-less permalinks via rewrite settings in a .htaccess file on the server for example.

For static pages without any further settings, you will need the extension or a directory with a index.html inside.

**Comment by penibelst** [comment]
> Is this documentation outdated?

This documentation is opinionated. You are free to design your URLs as you want.

**Comment by penibelst** [comment]
@tomjohnson1492 So you do *not* need `index.html` files to make Jekyll work.

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
