### ISSUE TITLE
Do any generators work with pages or collections?

### ISSUE THREAD

**Issue by tomjohnson1492** [jekyll/jekyll-help#260]
Are there any generators that work with pages or collections? I want to auto-generate a page that lists all pages that have a specific tag (like a tag archive but for pages instead of posts). Alternatively, I would like to auto-generate a collection archive (a page showing all pages in the collection). I know how to manually create these archive pages, but is there a way to auto-generate this kind of archive page on build? Ideally, it would work like this [categories archive plugin](https://github.com/recurser/jekyll-plugins) but for pages.

**Comment by sondr3** [comment]
https://github.com/jekyll/jekyll-archives

**Comment by tomjohnson1492** [comment]
Thanks, but does this work for pages, or just for posts? When I implement it, it seems to only create archives for posts.

**Comment by sondr3** [comment]
Oh, you wanted for pages too? Not to sure that this is possible right now with Jekyll as pages and posts are two different things when generated, this might change in 3.0 but I'm not sure.

**Comment by kleinfreund** [comment]
@tomjohnson1492 May I ask what kind of pages you have and why you want to why you want to put them together in an archive?

**Comment by tomjohnson1492** [comment]
I'm using jekyll for a documentation site (e.g., user guide). There are various sections in the user guide, such as Getting Started, Implementation, Configuration, Troubleshooting. I want to create different lists for pages in these sections. So I'm using tags with pages. I'm autopopulated my navigation sidebar like this:

```
<ul>
  {% assign counter = '0' %}
                {% assign pages = site.pages | sort: "weight"  %}
                {% for page in pages %}
                {% for tag in page.tags %}
                {% if tag == "Implementation" and counter < '9' %}
                {% capture counter %}{{ counter | plus:'1' }}{% endcapture %}
                  <li class="list-group-item"><a href="{{ page.permalink | prepend: site.baseurl }}">{{page.title}}</a></li>
                {% endif %}
                {% endfor %}
                {% endfor %}
</ul>
```

When there are more than 9 topics, I want to say something like "See all" and direct people to an archive view that contains all topics. 

Am I going about this the wrong way? Should I be using posts instead? I just don't want to have to put dates in all my post titles.

**Comment by sondr3** [comment]
Personally I think this would pretty easily be solved by having the pages be posts and have the permalink setting to be /:category/:name/ or something similar. Otherwise I think you might have to create separate pages manually and populate them yourself. You could possibly use a similar solution to how Jekyll organizes it's sidenav in the documentation on their website.

**Comment by kleinfreund** [comment]
What soundr3 sound5 logical. I did a very basic archive on my blog with my posts as well. Linking to the archive when there is 10 posts already.

**Comment by tomjohnson1492** [comment]
How are pages and posts changing in v3 of Jekyll? I'm not sure I totally understand the difference between the two. What I know is that posts are meant for chronological sorting, they have dates in file names, and they occupy a different namespace (posts instead of pages). Pages are meant to stand alone, they don't sort by filename, and they have a posts namespace. 

But it seems like more features are built are posts (like this plugin) since jekyll was initially conceived as a blogging platform, not a website/user-guide platform. Right?

**Comment by sondr3** [comment]
It's mostly a backend change as far as I know and I haven't really read much up on the specifics, but you can see the main issue here: jekyll/jekyll#3169.

**Comment by kleinfreund** [comment]
@tomjohnson1492 Yeah, I see your point. As far as I understand it, pages are meant to not have any relation between one and another. That's what collections _should_ be for.

**Comment by tomjohnson1492** [comment]
I understand how collections work, but I'm looking to develop a simple
template that doesn't require other writers to add collection types to a
configuration file. I think categories or tags on posts will work just fine
for me.

---------------------
blog: idratherbewriting.com
twitter: tomjohnson
408-540-8562

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
