### ISSUE TITLE
Paginator items not displaying properly

### ISSUE THREAD

**Issue by sr-murthy** [jekyll/jekyll-help#261]
Hi

At the moment the paginator items on `index.html` does not display properly, it looks like this

![hyde-paginator](https://cloud.githubusercontent.com/assets/9358070/5983082/caec6ec0-a8c1-11e4-99cb-b4017aee0221.png)

I don't know why it is stacking them vertically, the paginator code is unchanged from the hyde source https://github.com/poole/hyde (and so is the relevant CSS code in poole.css):

    <div class="pagination">
    {% if paginator.next_page %}
    <a class="pagination-item older" href="{{ site.baseurl }}page{{paginator.next_page}}">Older</a>
    {% else %}
    <span class="pagination-item older">Older</span>
    {% endif %}
    {% if paginator.previous_page %}
      {% if paginator.page == 2 %}
        <a class="pagination-item newer" href="{{ site.baseurl }}">Newer</a>
      {% else %}
        <a class="pagination-item newer" href="{{ site.baseurl }}page{{paginator.previous_page}}">Newer</a>
      {% endif %}
    {% else %}
      <span class="pagination-item newer">Newer</span>
    {% endif %}
    </div>

**Comment by nternetinspired** [comment]
This is clearly a question for the Hyde author, as neither that paginator code nor the associated css exists in Jekyll's default template, and I see you've already created an issue there: https://github.com/poole/hyde/issues/80

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
