### ISSUE TITLE
Controlling the length/size of post excerpts on index.html

### ISSUE THREAD

**Issue by sr-murthy** [jekyll/jekyll-help#262]
Hi

At the moment I use post excerpts on `index.html` on my Jekyll site http://sandeepmurthy.is, but I am not completely happy with the apparently arbitrary way in the lengths of the excerpts seem to vary.  For some posts, like one with an inline image in the first paragraph, the excerpts seem to be much longer than others where the first paragraph is pure text.  For posts where there is a single large image, the excerpt includes all of that, rather than just showing part of the image.

Is there a way to control the size of an excerpt?

Sandeep

**Comment by kleinfreund** [comment]
Yes, there is. The default excerpt seperator are two newlines (`\n\n`). You can change this in your config.

**Comment by sr-murthy** [comment]
Thanks, it works.

**Comment by sr-murthy** [comment]
Hi,

just a final question, is there a similar property for controlling the space between posts.  At the moment I'd like to be able to have my posts to be spaced a bit more closely in `index.html` but there seems to be no way of controlling this via the code:

    <div class="posts">
    {% for post in paginator.posts %}
        <div class="post">
        <h1 class="post-title">
          <a href="{{ post.url }}">{{post.title}}</a>
        </h1>
        <span class="post-date">{{ post.date | date_to_string }}</span>
        {{ post.excerpt }}<a href="{{ site.url }}{{ post.url }}">....</a>
        </div>
    {% endfor %}
    </div>

**Comment by jaybe-jekyll** [comment]
CSS.

**Comment by kleinfreund** [comment]
> CSS.

These things are controlled via CSS, correct. For example, you could change the `line-height` on the `html` element. I usually prefer more room between my lines and have something like `line-height: 1.5;`.

**Comment by sr-murthy** [comment]
OK, thanks.
