### ISSUE TITLE
jekyll-3.0.0.pre.beta

### ISSUE THREAD

**Issue by frall8** [jekyll/jekyll-help#265]
/Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta1/lib/jekyll.rb:33:in `<top (required)>': undefined method `error_mode=' for Liquid::Template:Class (NoMethodError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta1/bin/jekyll:6:in `<top (required)>'
	from /usr/bin/jekyll:23:in `load'
	from /usr/bin/jekyll:23:in `<main>'

**Comment by alfredxing** [comment]
Can you try running `bundle install` to see if that fixes it?

**Comment by parkr** [comment]
It's possible that Jekyll loaded Liquid 2 instead of Liquid 3. Make sure you've uninstalled Liquid 3 from your system or are using Jekyll with Bundler.

**Comment by crearc** [comment]
I'm receiving the same error. I use Bundler and I made sure all the packages were up to date.

**Comment by crearc** [comment]
@frall8 did you find a solution?

**Comment by parkr** [comment]
@crearc What liquid version is in your bundle?

**Comment by crearc** [comment]
liquid (3.0.1) straight from my Gemfile.lock

**Comment by parkr** [comment]
@crearc What did you run? `bundle exec jekyll build`?
