### ISSUE TITLE
Jekyll Build site doesn't seems to be right

### ISSUE THREAD

**Issue by ppazos** [jekyll/jekyll-help#267]
I'm testing Jekyll, created a site, it seems to have some sample content and it looks great when I run jekyll serve.

![screen shot 2015-02-05 at 7 42 34 pm](https://cloud.githubusercontent.com/assets/1278556/6069897/4851bfd0-ad6f-11e4-9dc9-dd624c1fae4e.png)

Then, when I do jekyll build and I open _site/index.html, the site looks terrible this (no errors on build):

![screen shot 2015-02-05 at 7 42 10 pm](https://cloud.githubusercontent.com/assets/1278556/6069904/4f79f3f4-ad6f-11e4-9883-1f573d28a2bc.png)
![screen shot 2015-02-05 at 7 42 51 pm](https://cloud.githubusercontent.com/assets/1278556/6069906/524c8f1a-ad6f-11e4-88f5-b08937290caa.png)

Any ideas why this is happening?

**Comment by kleinfreund** [comment]
Yeah, check the URLs in the source. They are root relative, not file relative. Thus previewing the site template with the local files without a local server doesn't work.

**Comment by kyrsideris** [comment]
I had exactly the same problem and `site.url` or `site.baseurl` inside `_config.yml` were looking sane. What I did to overcome the problem was, as @kleinfreund suggested, to `prepend: site.url` or/and `site.baseurl` whenever was missing.
The main damage to your css comes from `_includes/head.html` which should be changed from:
```html
<link rel="stylesheet" href="{{ "/css/main.css" | prepend: site.baseurl }}">
```
to:
```html
<link rel="stylesheet" href="{{ "/css/main.css" | prepend: site.baseurl | prepend: site.url }}">
```
Hope that helps!

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
