### ISSUE TITLE
Lots of white space -- will it affect performance?

### ISSUE THREAD

**Issue by tomjohnson1492** [jekyll/jekyll-help#269]
I have some code like this:

```
<li><a href="#">Scenarios</a>
<ul>
{% for page in site.pages | sort: "weight" %}
{% for tag in page.tags %}
{% if tag == "Scenarios" %}
<li><a class="post-link" href="{{ page.url | prepend: site.baseurl }}">{{ page.title }}</a></li>
{% endif %}
{% endfor %}
{% endfor %}
</ul>
</li>
```

When I view the source of the generated HTML, there's a TON of blank lines. Is that normal? Doesn't that affect performance?

**Comment by alfredxing** [comment]
It is normal, since Liquid repeats newlines and whitespace in loops.

From what I know, the only downside to increased page size from whitespace is increased loading (downloading) time. From experience, this increase in time is extremely small (especially if gzip is enabled), and shouldn't be an issue at all.

**Comment by budparr** [comment]
I think @penibelst has done some work on solving this issue: https://github.com/penibelst/jekyll-compress-html

**Comment by penibelst** [comment]
As @budparr mentioned you can remove whitespaces and other optional thing by using my Compress Layout.

@alfredxing The download performance affect is small, but performance is more than downloading: gzipping itself, rendering, and caching, especially on small devices, depend on the *raw* file size.

**Comment by alfredxing** [comment]
@penibelst True, thanks for the comment!

**Comment by kleinfreund** [comment]
It's worth mentioning the case of hosting on GitHub Pages: Content will be gzipped automatically.

**Comment by troyswanson** [comment]
Throughly answered, gents. Thanks!
