### ISSUE TITLE
How do you properly enable syntax highlighting for Objective-C code?

### ISSUE THREAD

**Issue by ronak2121** [jekyll/jekyll-help#271]
I've been trying to input Objective-C code into Jekyll but am not able to properly get the syntax highlighting working.

None of the following seem to do anything:

```objective-c
```objc
```objectivec

How do you let Jekyll know about objective-c code?

**Comment by ronak2121** [comment]
To clarify, it looks like it doesn't detect comments, @interface, @end, @implementation objective-c constructs.

**Comment by kleinfreund** [comment]
@ronak2121 On a side note, at would be helpful to format `@interface`, `@end` and `@implementation` as code, because you just notified these people about this issue. They probably don't have anything to do with it.

**Comment by kleinfreund** [comment]
@ronak2121 Did you manage to resolve this issue? It would help future visitors to tell them what you needed to do.

Otherwise, feel free to reopen this one.

**Comment by ronak2121** [comment]
Well I thought that I could fix this by using:

{% highlight objective-c %}

{% endhighlight %}

but that doesn't format anything really.

Do I have to add any css or Javascript to the page to enable this?

**Comment by kleinfreund** [comment]
Do you have a highlighter set in your config?

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
