### ISSUE TITLE
Table of contents on left hand side of page....

### ISSUE THREAD

**Issue by abadger1406** [jekyll/jekyll-help#273]
My goal is to use jekyll to manage some documentation, ideally want a [read-the-docs](http://bootstrap-datepicker.readthedocs.org/en/master/markup.html) style with table of contents generated automaticallly for each page from the headers within that page.

I'l like a TOC generated that I can place where I wish in my page. I'm new to Jekyll, so added the https://github.com/dafi/jekyll-toc-generator to generate a TOC - which is great. But this appears to only allow the toc to be placed on top of the page. I think I want the plugin to only output a toc, so this can be placed anywhere  in page. Maybe this functionality already exists within this plugin - but I don't see how to position the TOC on the page.

I.E {{ content | toc_generate }} gives you the whole toc + page ....I would like to use this to just give the toc, and then use {{ content }} to put the actual page in. I think this would be a trivial change to the plugin - but I struggling to see how to make this change - or if this is the correct approach.

Many Thanks in advance Dave

**Comment by tomjohnson1492** [comment]
Can't you just put the TOC code into your sidebar?

**Comment by abadger1406** [comment]
The TOC code is generated by the plugin, which then outputs the html with the TOC code added to the top. So there is no obvious way to just get the TOC code ? I guess I want to edit the toc_generate plugin to do this, but am unsure how.

I.E the following layout will give the whole page twice - once in the left side-bar with toc at top...and again the whole page in the main section:-

```
% Cat _layouts/default.html
<!DOCTYPE html>
<html>

  {% include head.html %}

  <body>

    {% include header.html %}

    <div class="page-content">
      <div id="left-side">
        {{ content | toc_generate }}
      </div>
      <p>here</p>
      <div class="wrapper">
        {{ content }}
      </div>
    </div>

    {% include footer.html %}

  </body>

</html>
```

**Comment by mmistakes** [comment]
Not sure what Markdown converter you're using, but Kramdown can automatically [generate a table of contents](http://kramdown.gettalong.org/converter/html.html#toc) for you. It gives you control over the placement of the toc too, you just place a `{:toc}` tag where you'd like it to appear and Kramdown does the rest.

There are also several [Javascript solutions](http://www.sitepoint.com/5-jquery-table-content-toc-plugins/) that can do the same thing.

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
