### ISSUE TITLE
Generate pages from a property of _data/file.yml?

### ISSUE THREAD

**Issue by mvaneijgen** [jekyll/jekyll-help#274]
I have a _date/file.yml with 200+ entries and all of them have a 'tag' property. Is it possible to create a page for every value of the 'categorie' property without know what they are? 

There are around 10 different tags, so I could just create 10 pages and loop through them accordingly, but it seems smarter to automate the process.

Is this possible to do without the use of a plugin, so I can keep hosting it on gh-pages?

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
