### ISSUE TITLE
"undefined method 'frontmatter_defaults'" 

### ISSUE THREAD

**Issue by skagedal** [jekyll/jekyll-help#275]
Hi!

I'm trying to build the jekyll-based manual for a program called Ardour. [Here is the github repo for the manual](https://github.com/Ardour/manual). 

I'm using jekyll 2.5.3 installed via gem on an Ubuntu 14.10 machine. However, I'm running into various problems. First, it couldn't find the plugins even though they're in the suppost default directory "_plugins"; I had to set it explicitly. Then I ran into a problem "undefined method `frontmatter_defaults' for nil:NilClass" - please see [this bug report](http://tracker.ardour.org/view.php?id=6167) at the Ardour bug tracker for details. Any clues what's going on?

**Comment by willnorris** [comment]
Regarding your first question... by default, jekyll expects to find your `_plugins` folder inside your `source` folder (alongside `_layouts`, `_posts`, etc).

**Comment by skagedal** [comment]
Allright, thanks! So that problem makes sense then.

**Comment by willnorris** [comment]
So, as alluded to in the error message, `@site` is nil when called [here](https://github.com/Ardour/manual/blob/0b6ad9326ccdaec578164df288c8ce6321ca67a0/_plugins/manual.rb#L72), which is ultimately what's throwing the error.  This `manual.rb` plugin is really convoluted... it would probably be much better to set these up as standard jekyll pages and come up with a simpler approach to build the TOC (there are a number of TOC plugins out there)

**Comment by skagedal** [comment]
Thank you, Will! This helped me craft up a hack (see [Ardour bug report](http://tracker.ardour.org/view.php?id=6167) in case you would be interested). Now of course the next problem surfaced... :) And yes, it seems to me as well there would be simpler ways of doing this closer to the standard jekyll scenario, thanks for confirming that. The TOC plugins I can find when googling however is for building a TOC of a single page, not for a hierarchy of pages.... But anyway, I guess I can close this issue. 

To think out loud, my choices at this point seem to be: 1. try to see if I can get the same old version of jekyll as the Ardour devs are using; 2. keeping trying with some ugly hacks; 3. actually learn Ruby. :)
