### ISSUE TITLE
Solo theme won't build in user pages? 

### ISSUE THREAD

**Issue by jamesonzimmer** [jekyll/jekyll-help#276]
Hi, I'm trying to setup a user pages for my brother based on the jekyll theme Solo (http://solo.chibi.io). I had set it up so he can edit the index.md file via prose.io whenever he likes, however gh-user pages doesn't seem to be building changes to the index.md file! Prose edits the file, but it doesn't build to _site. Strangely it seems to work fine on my local jekyll server, so I'm not sure what I can do to make it build. 

repo is at https://github.com/SeanZimmer/seanzimmer.github.io

Any ideas for edits to the config file or structure that could fix this? (I know he could just build via command line, but that's a bit technical for him.) Thank you!

**Comment by kleinfreund** [comment]
> however gh-user pages doesn't seem to be building changes to the index.md file!

Just to be sure, the branch you have the site on is called __gh-pages__ (not gh-user), right?

**Comment by jamesonzimmer** [comment]
Yeah, it's on master branch at his github account under seanzimmer.github.io, since my understanding is you don't make a gh-pages branch for user pages.
