### ISSUE TITLE
After migration, how can I redirect old URLs to new ones?

### ISSUE THREAD

**Issue by verlok** [jekyll/jekyll-help#282]
Hi,
I'm migrating my blog from Wordpress to Jekyll, but I'm concerned about preserving old URLs from 404.

The ideal would be to redirect old URLs, which are not many (about 20), to the new ones with a 304.
How can I do this?

**Example:**
* Old URL: http://www.andreaverlicchi.eu/advanced-sprite-generation-using-compass-sass/
* New URL: http://www.andreaverlicchi.eu/development/2015/03/06/advanced-sprite-generation-using-compass-sass.html
...

I don't expect to do the "old URL - new URL" association automatically... no problem to do it automatically, but I'd like to know what is the best way to do the redirect.

**Additional info:**
My site is hosted on a linux server supporting PHP.

**Comment by willnorris** [comment]
It won't give you the `30x` response codes, but https://github.com/jekyll/jekyll-redirect-from provides a pretty simple way to redirect from old URLs.  It does a client-side redirect, which I'm fairly certain Google still treats like a 301 redirect, so you still get the SEO benefits.

If you still really want the `30x` response code, you'll need to do it in your web server itself.

**Comment by albertogg** [comment]
Yes, +1 to @willnorris, this is may be easiest way to do it, you should give it a try and see if you like it or not... if you'll be hosting your own jekyll blog you can also use apache htaccess or nginx to do this. Hope this helps.

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
