### ISSUE TITLE
How do I use variables with Liquid in Jekyll?

### ISSUE THREAD

**Issue by tomjohnson1492** [jekyll/jekyll-help#283]
I want to use a variable inside a `for` loop, like this:

```
{% capture sidebar %}
site.data.sidebar_fe.entries
{% endcapture %}

{% for entry in sidebar %}
```
Basically here I want to set up a variable called `sidebar` that really refers to `site.data.sidebar.fe.entries`.

However, this doesn't work. Any ideas why? I thought `capture` was how I set up a variable.

**Comment by troyswanson** [comment]
You might want to try using `assign` instead of `capture`

**Comment by kleinfreund** [comment]
Yeah, `assign` is what you want. This is what I do:

```liquid
{% assign page-lang = site.data.locales[page.lang] %}
```

`page.lang` is either `de` or `en` and I have a YAML file in `_data` that has a structure like this:

```yaml
de:
  whatever: 'Ding'

en.
  whatever: 'thing'
```

**Comment by tomjohnson1492** [comment]
Awesome! Thanks, that does work. I appreciate your quick response. 

Here's the code I used. Basically I have an audience value defined in my config file. Depending on the audience, different sidebars are called:

```
{% if site.audience == "fe" %}
{% assign sidebar = site.data.sidebar_fe.entries %}

{% elsif site.audience == "customer" %}
{% assign sidebar = site.data.sidebar_customer.entries %}
{% endif %}

{% for entry in sidebar %} ...
```

Thanks for your help.

**Comment by troyswanson** [comment]
:boom: :metal:
