### ISSUE TITLE
Include tags not rendering when called from plugin

### ISSUE THREAD

**Issue by egardner** [jekyll/jekyll-help#284]
I'm trying to write a basic generator plugin that creates a JSON version of each page in my site.
I've got this working, with one exception: `{% include %}` tags in the content of the pages are not being rendered when the JSON version of a page is created.

These tags **are** being rendered when Jekyll creates the standard HTML version of the pages, however, so I don't understand what I'm missing. 

Here's the content of my plugin file (adapted from [here](https://github.com/jgarber623/sixtwothree.org/blob/master/src/_plugins/json_page_generator.rb):

```ruby
module Jekyll
  class JSONPage < Page
    def initialize(site, base, dir, name, content)
      @site = site
      @base = base
      @dir  = dir
      @name = name

      self.data = {}
      self.content = content

      process(@name)
    end

    def read_yaml(*)
      # Do nothing
    end

    def render_with_liquid?
      false
    end
  end

  class JSONPostGenerator < Generator
    safe true

    def generate(site)
      
      site.pages.each do |page|
        if page.html?

          path = page.destination("").sub ".html", ".json"

          output = page.to_liquid

          output['content'] = page.transform

          site.pages << JSONPage.new(site, site.source, File.dirname(path), File.basename(path), output.to_json)
        end
      end

    end

  end
end
```
In each of my pages, I'm calling one or more `include` tags in the markdown content of the page and passing params. For example:

```liquid
{% include compare.html first_figure="1a" second_figure="1b" %}
```

The HTML output of `jekyll build` renders that line as the following HTML:
```html
<figure class="compare">
  <img class="lazyload" data-src="images/001a.jpg" alt="Figure1a" id="fig1a" />
  <img class="lazyload" data-src="images/001b.jpg" alt="Figure1b" id="fig1b" />
  <figcaption>
    <span><strong>Figure 1a.</strong> Riace Bronze A. Greek, mid-5th century B.C. H: 1.98 m (ca. 6½ ft.).Reggio Calabria, Museo Nazionale.</span>
    <span><strong>Figure 1b.</strong> Riace Bronze B. Greek, mid-5th century B.C. H: 1.97 m (ca. 6½ ft.).Reggio Calabria, Museo Nazionale.</span> 
  </figcaption>
</figure>
```

This is all working as it should. However, the JSON output of the same page (which is otherwise correct, complete with front-matter properly formatted) still has the raw `{% include compare.html %}` in its content; it's not being rendered by Jekyll.

I would assume that calling `page.transform` in the plugin would "transform" this particular content, but that's not happening. Any ideas?

Sample (abbreviated) JSON output below – HTML content is otherwise rendering, escaping, etc. – but Jekyll-specific `{%include%}` syntax is untouched...

```json
{
  "id": 0,
  "title": "Foreward",
  "cover_image": "023.jpg",
  "content": "<p>Fact and fiction mingle in the classical myth of Talos, a Cretan giant made of bronze... </p>\n\n<p>{% include compare.html first_figure=\u201d1a\u201d second_figure=\u201d1b\u201d %}</p>"
}
```

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
