### ISSUE TITLE
Installing Jekyll is out-dated

### ISSUE THREAD

**Issue by starius** [jekyll/jekyll-help#286]
I'm trying to follow [instructions][1] to install Jekyll.
I'm using ruby 1.9.1
I got the following error:
```
ERROR:  Error installing github-pages:
        public_suffix requires Ruby version >= 2.0.
```
This error happens if I run `bundler install` or `gem install github-pages`.

I think, it is a result of new version of public_suffix, released Mar. 25, 2015.
I've found the following workaround: `gem install public_suffix -v 1.4.6`

After this, command `gem install github-pages` succeeded.

[1]: https://help.github.com/articles/using-jekyll-with-pages/#installing-jekyll

**Comment by albertogg** [comment]
Hi @starius, I believe Jekyll will install with no issues under Ruby >= 2.0... that said it seems that you did a work around and worked. Remember to update your Ruby to 2.0+ if you still have any issues.

**Comment by starius** [comment]
I believe that the issue is not fixed. [The instruction][1] says the following:

> Your Ruby version should begin with 1.9.3 or 2.0.0.

This part is invalid, because the instruction doesn't  work with Ruby 1.9.3, if you don't apply the workaround, which isn't mentioned in the instruction.

> Remember to update your Ruby to 2.0+

Easier said than done. This would require me to upgrade gcc to 4.9, which means upgrading almost all packages from Debian Wheezy to Debian Testing. I use my workaround and want to share it with other users of Ruby 1.9.

Could you change the instruction, please? I think, it worth to mention about the problem with Ruby 1.9 and the workaround. Or you can remove `should begin with 1.9.3` part from the instruction.

[1]: https://help.github.com/articles/using-jekyll-with-pages/#installing-jekyll

**Comment by albertogg** [comment]
@starius, current stable jekyll (version 2.5.x) does work under Ruby 1.9.3... but this [ruby has reached the end of life](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/) and I will not advice installing a not supported ruby... That said, documentation for this version is correct. Remember that if you find any issues with the documentation you can submit a pull request to fix this.

**Comment by KurtPfeifle** [comment]
I currently have the same issue on OS X with...

1. ...first a Ruby v1.9.3 (installed via MacPorts)
1. ...second the system-provided Ruby v2.0.0 (installed by Apple)
1. ...third, a Ruby v2.0.0 (installed via MacPorts)
1. ...fourth, a Ruby v2.2.2 (installed via MacPorts)

I'll now try the workaround...

**Comment by KurtPfeifle** [comment]
Nope -- the workaround proposed by @starius doesn't work here. For neither version of Ruby.

Because meanwhile I also tested said "workaround" in combination with a (reverted back to) Ruby v1.9 and an additionally installed Ruby v2.1.

    kp@mbp:>  sudo gem install public_suffix -v 1.4.6
      Fetching: public_suffix-1.4.6.gem (100%)
      Successfully installed public_suffix-1.4.6
      1 gem installed
      Installing ri documentation for public_suffix-1.4.6...
      Building YARD (yri) index for public_suffix-1.4.6...
      [warn]: Could not find readme file: README.rdoc
      Installing RDoc documentation for public_suffix-1.4.6...

    kp@mbp:>  ruby --version
      ruby 2.0.0p645 (2015-04-13 revision 50299) [x86_64-darwin13]

    kp@mbp:>  gem list public_suffix
      *** LOCAL GEMS ***
      public_suffix (1.4.6)

    kp@mbp:>  sudo gem install github-pages
      Fetching: github-pages-health-check-0.3.0.gem (100%)
      Fetching: terminal-table-1.4.5.gem (100%)
      Fetching: github-pages-34.gem (100%)
      ERROR:  Error installing github-pages:
              github-pages requires Ruby version >= 2.0.0.

    kp@mbp:>  sudo port -pf install ruby21
    kp@mbp:>  sudo rm -rf /opt/local/bin/ruby
    kp@mbp:>  sudo ln -s /opt/local/bin/ruby2.1 /opt/local/bin/ruby
    
    kp@mbp:>  ruby --version
      ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin13]

    kp@mbp:>  gem list public_suffix
      *** LOCAL GEMS ***
      public_suffix (1.4.6)

    kp@mbp:>  sudo gem install github-pages
      ERROR:  Error installing github-pages:
	          github-pages requires Ruby version >= 2.0.0.

    kp@mbp:>  sudo rm -rf /opt/local/bin/ruby
    kp@mbp:>  sudo ln -s /opt/local/bin/ruby1.9 /opt/local/bin/ruby
    
    kp@mbp:>  ruby --version
      ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-darwin13]

    kp@mbp:>  gem list public_suffix
      *** LOCAL GEMS ***
      public_suffix (1.4.6)

    kp@mbp:>  sudo gem install github-pages
      ERROR:  Error installing github-pages:
	          github-pages requires Ruby version >= 2.0.0.

    kp@mbp:>  port installed ruby*
      The following ports are currently installed:
        ruby @1.8.7-p374_0+dtrace+tk (active)
        ruby19 @1.9.3-p551_0+c_api_docs+doc+tk (active)
        ruby20 @2.0.0-p645_0+doc (active)
        ruby21 @2.1.6_0+doc (active)
        ruby22 @2.2.2_0+doc (active)
        ruby_select @1.0_0 (active)

**Comment by starius** [comment]
Hi @KurtPfeifle,

>   ERROR:  Error installing github-pages:
>          github-pages requires Ruby version >= 2.0.0.

This requirement changed in [github-pages version 34][34], released April 8, 2015, after my comments were written (March 28, 2015 and April 3, 2015).

Try to set github-pages's [version 33][33]:

```bash
$ sudo gem install github-pages -v 33
```

By the way make sure that `gem` tool is also updated, when you update `ruby`. As I remember, they can be of different versions... I don't have Mac to check it though. 

[33]: https://rubygems.org/gems/github-pages/versions/33
[34]: https://rubygems.org/gems/github-pages/versions/34

**Comment by snarkmaster** [comment]
Ubuntu 14.04.1 LTS packages Ruby 1.9.3, so this problem will continue well into 2019 (https://wiki.ubuntu.com/LTS). So much for "end of life", huh?

**Comment by kleinfreund** [comment]
That said, you should update your Ruby version. The current version is 2.2.2.
