### ISSUE TITLE
Installing Jekyll

### ISSUE THREAD

**Issue by apollotull** [jekyll/jekyll-help#287]
Hello... I have run a sudo gem install to begin using jekyll, however i keep getting the error message "Failed to build a gem native extension." Any ideas how to fix this?

**Comment by jamesonzimmer** [comment]
Depends on what OS you're using I'd imagine, maybe try some of the suggestions from this thread: http://stackoverflow.com/questions/22544754/failed-to-build-gem-native-extension-installing-compass

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
