### ISSUE TITLE
How to Change Your Homepage from Recent Posts to About?

### ISSUE THREAD

**Issue by DanielRoberts95** [jekyll/jekyll-help#289]
I have been messing around with the [Long-Haul](http://brianmaierjr.com/long-haul/) theme for Jekyll lately and I want to make "About" the homepage, not the standard "Recent Posts" page (which I want to instead put in a Blog section). Does anyone know how to do this? Any help is greatly appreciated. :)

The repository for Long-Haul is [here](https://github.com/brianmaierjr/long-haul).

**Comment by tomjohnson1492** [comment]
The index file in the root directory gets rendered as the homepage. Maybe just take the existing code out of that file and put it into a new page called "Recent Posts." Then move the content from your About page into that index page (and delete the About page).

**Comment by DanielRoberts95** [comment]
I've tried doing that but the problem is that there are two index.html files by default that are used to create the Recent Posts page. There's one in the root directory and one in the _sites folder. The one in the _sites folder is what actually shows up when I run the command Jekyll serve, but the one in the root folder is used to take what you put in the _posts folder onto the page. I'm new to Jekyll so I'm not really sure why this is, but if you want you can check out the Long-Haul repository and see what I'm talking about [here](https://github.com/brianmaierjr/long-haul).

**Comment by tomjohnson1492** [comment]
All the content in the _site folder is where Jekyll builds your site. You never edit those files, since that folder's contents is deleted and regenerated each time you rebuild your site.

Looking in index.html, this is the code that is getting your recent posts (along with pagination):

```
 <ul class="posts noList">
          {% for post in paginator.posts %}
            <li>
            	<span class="date">{{ post.date | date: '%B %d, %Y' }}</span>
            	<h3><a href="{{ site.url }}{{ post.url }}">{{ post.title }}</a></h3>
            	<p class="description">{% if post.description %}{{ post.description  | strip_html | strip_newlines | truncate: 250 }}{% else %}{{ post.content | strip_html | strip_newlines | truncate: 250 }}{% endif %}</p>
            </li>
          {% endfor %}
        </ul>
        <!-- Pagination links -->
        <div class="pagination">
          {% if paginator.previous_page %}
            <a href="{{ site.url }}{{ paginator.previous_page_path }}" class="previous button__outline">Newer Posts</a>  
          {% endif %} 
          {% if paginator.next_page %}
            <a href="{{ site.url }}{{ paginator.next_page_path }}" class="next button__outline">Older Posts</a>
          {% endif %}
        </div>
```
Just remove this content and replace it with your About information. Create a new page and stick this content in there. See how it works.

**Comment by DanielRoberts95** [comment]
While that did work for putting the About page content on the homepage (thank you!) this is what the Blog page looks like for some reason.
![atfirst](https://cloud.githubusercontent.com/assets/11403206/7107236/073aa3b2-e114-11e4-9e31-96d64443ed9b.png)

This is what the index.html code looked like originally in the blog.md
![originalcode](https://cloud.githubusercontent.com/assets/11403206/7107254/bb3f06be-e114-11e4-93c3-486ced21fb3a.png)

I then changed the indentation of the code (by just pressing backspace in front of a lot of the code) which changed it to this:
![fixedindentation](https://cloud.githubusercontent.com/assets/11403206/7107258/d125ba72-e114-11e4-82f2-75a1c6a862a4.png)

Doing so changed the page to this, just making the entirety of the Blog page blank:
![after](https://cloud.githubusercontent.com/assets/11403206/7107267/2c9f0ed0-e115-11e4-97ff-df6d9029f425.png)

Thank you so much for all of your help so far by the way :)

**Comment by tomjohnson1492** [comment]
Markdown files process spacing as syntax (two spaces to the left sets off text as code), so that's why pasting the code into an md file initially probably set it off as code. you have to remove all the spacing to the left at the start of the first element and the last element. I believe you did that, so I'm not sure why it's not rendering. I would play around with the spacing a bit more. 

Might be easier to change the file extension from .md to .html for that recent posts file.

(I assume you registered the collection (paginator) in your config file.)

**Comment by DanielRoberts95** [comment]
I messed around with the spacing a bit more, here's what the blog.md file looks like now:
![blogmd](https://cloud.githubusercontent.com/assets/11403206/7107378/ae75be10-e118-11e4-8b55-d2e77dad26b9.png)
From what I see the only difference is that it registered the HTML comment as a comment, unfortunately it did not change anything and the Blog page is still blank.

I tried changing the file extension from .md to .html in the blog file but the page is still blank.

Here's a screenshot of my config.yml file if you're interested.
![config](https://cloud.githubusercontent.com/assets/11403206/7107397/4b9bf88a-e119-11e4-9089-1f41764c3b1c.png)

**Comment by tomjohnson1492** [comment]
Sorry, I haven't actually worked with pagination much, so I incorrectly assumed something about a collection that wasn't the case at all. The paginator reference is a feature of Jekyll for paginating blog posts (e.g., showing 10 per page or something). See [http://jekyllrb.com/docs/pagination/](http://jekyllrb.com/docs/pagination/). See esp. the Enable Pagination section. 

I am not sure how to reconfigure pagination on a page other than the homepage. I would assume it's possible -- I just don't know how. Maybe look at another theme to see how it's done?

As a short term fix, you could just change the following line in the recent posts code: 

```
{% for post in paginator.posts %}
```
to this:

```
{% for post in site.posts %}
```

Then it works. Not sure how you get pagination, though. On my site, for the blog archive, I just point to a page that will list a bunch of old posts:

```
<div class="home-read-more">
  <a href="{{ "/archive" | prepend:site.baseurl }}" class="btn btn-primary btn-lg">View All {{ site.posts | size }} Articles →</a>
</div>
```
As I said, I am primarily working with pages to build out a doc theme, not using Jekyll for a blog (not yet anyway).

Tom

**Comment by DanielRoberts95** [comment]
It works, thanks! Yeah I'm not sure how to get pagination either, but I will try my best to figure it out. Thank you so much for all of your help! :)

**Comment by jamesonzimmer** [comment]
FYI to my knowledge, pagination only works with files in your 'post' folder
via a 'for' liquid loop. Probably you already know this though :-).

I found the Poole theme (http://getpoole.com) really useful for figuring
out proper ways to use pagination. Also you can get endless scroll hooked
up pretty easy: https://github.com/tobiasahlin/infinite-jekyll

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
