### ISSUE TITLE
How can I capture the link of the current post?

### ISSUE THREAD

**Issue by zotherstupidguy** [jekyll/jekyll-help#290]
Hi, I would like to add a link to the posts layout, so that it will contain a link to the markup page link of the post hosted on github.

This provides easy access for editing. How can this be done? I checked page.date and page.title but coucln't parse them in a way that mimics the github url schema.

**Comment by zotherstupidguy** [comment]
Also is it possible to use ruby's #{} in jekyll?

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
