### ISSUE TITLE
Using SASS files from gems installed with bundler

### ISSUE THREAD

**Issue by astehlik** [jekyll/jekyll-help#292]
I'm wondering if this is possible: I'm installing the [GitHub](http://github.com) gem by adding it to my ```Gemfile```:

```
source 'https://rubygems.org'
gem 'github-pages'
gem 'bootstrap-sass', '~> 3.3.4'
```

Then i call ```bundle install```.

But I don't get how I now can access the installed SASS files within Jekyll. How do I import the bootstrap SASS file from

```
/var/lib/gems/2.1.0/gems/bootstrap-sass-3.3.4.1/assets/stylesheets
```

in my local SASS files?

**Comment by budparr** [comment]
I *think* you might have to install with bower to use it in Jekyll. Then just add to your config and Jekyll will build it for you http://jekyllrb.com/docs/assets/#sassscss I'd point you to a repo to look at, but I use bourbon.

**Comment by astehlik** [comment]
Thank you for your reply!

Using bower is what I did actually to solve the problem :)

I was just curious if there is a possibility to use the files from the gem.

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
