### ISSUE TITLE
Sorting yaml front matter variable with heterogeneous data

### ISSUE THREAD

**Issue by DonnieWest** [jekyll/jekyll-help#295]
I am creating a simple song site with Jekyll and my songs are represented as posts with the following front matter:
```
---
layout: post
title: "My Song"
date: 2015-05-05T13:40:02-05:00
song: 3
---
```
I am porting over old paper bound books to this site, and unfortunately the songs are ordered by both number and letters (The song above could be 3 or it could be "A"). My attempts to sorting them are failing.

When doing this:
```{% assign posts = site.posts | sort:'song' %}```

It throws this error:
```Error: comparison of Jekyll::Post with Jekyll::Post failed```

Any way I can work around this?

**Comment by budparr** [comment]
Try putting quote marks around the song value, like ```song: '3'```

**Comment by DonnieWest** [comment]
Duh. Thank you!
