### ISSUE TITLE
problem with installing jekyll on windows

### ISSUE THREAD

**Issue by amysidra** [jekyll/jekyll-help#296]
C:\Users\amysidra>gem install jekyll
ERROR:  While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
    no such name (https://api.rubygems.org/quick/Marshal.4.8/jekyll-2.5.3.gemspe
c.rz)

**Comment by parkr** [comment]
Sometimes there's a problem getting to RubyGems from Southeast Asia: https://github.com/jekyll/jekyll/issues/1409

```text
$ gem sources --remove http://rubygems.org/
$ gem sources -a http://ruby.taobao.org/
$ gem sources -l
*** CURRENT SOURCES ***
http://ruby.taobao.org    
$ gem install rack 
```
