### ISSUE TITLE
TOC from GFM

### ISSUE THREAD

**Issue by tonysneed** [jekyll/jekyll-help#298]
I would like to have Jekyll generate a table of contents based on headers in a markdown file. I've tried several things based on some research, but no luck. Can anyone point me in the right direction? This is for GitHub Pages.

**Comment by tomjohnson1492** [comment]
I show how to create a table of contents in this documentation-oriented theme: https://github.com/tomjohnson1492/documentation-theme-jekyll

You use a data file with various levels. Then you use a for loop in your theme to iterate over the levels and get the right levels. 

I also incorporate the navgoco jquery plugin.

**Comment by tonysneed** [comment]
Hi Tom,

I took a look at your theme, and I very much like it.  My main question would be whether your approach would be compatible with GitHub Pages, as I'm not sure they include the required plugins.  Would you happen to know?

Cheers,
Tony

**Comment by tomjohnson1492** [comment]
The theme doesn't have any plugins. You just need to put one of the configuration files into the root and rename it _config.yml so github pages can build it.

**Comment by tonysneed** [comment]
Terrific, I'll give it a try!

**Comment by tomjohnson1492** [comment]
Just curious,  are you a technical writer of some kind? What is it about the theme that appeals to you?

**Comment by tonysneed** [comment]
I'm writing documentation for one of my open source projects on GitHub, and I'm dissatisfied with the suitability of the default themes for use with a programming reference.

One shortcoming has been the outlining.  For example, I would like to have a numbered list with bulleted items for each number, as well as images and code sections.  But the numbering will restart when followed by bulleted items, and the indenting past the first level didn't look right.

So my main question would be how to get your theme to work with GitHub Pages.  I read that you don't recommend it for multiple outputs.  But what I like about it, is that I can just push my changes to the repo, and GitHub will automatically build the doc site.  Would it be possible to just have a single level with all my md files in one place and a _config.yml file at the root?  My documentation does not include many pages.

Otherwise, are there other hosting options GitHub hooks that can be used to trigger a build and deployment of the doc site after pushing changes to the GitHub repo?

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
