### ISSUE TITLE
Jekyll Liquid interface

### ISSUE THREAD

**Issue by knsam** [jekyll/jekyll-help#300]
Dear Jekyll-help: 

I have spent frustrating hours trying to do what I think is simple. I have a YFM variable called `navbar_links` which is a list of strings. Each of these strings is a key in a file in `_data` named `navbarlinks.yml`. I would like to retrieve the value of each of the key in the list `navbar_links`. 

Any help would be appreciated. 

Thanks.

**Comment by kleinfreund** [comment]
How is the front matter (your navbar links)  formatted?

**Comment by knsam** [comment]
Do you mean the file `navbarlinks.yml`?

~~~
- name: "Home"
  url: "/"

- name: "About"
  url: "/about/"
~~~

and I include a `nav.html` which is a partial with the following code: 

~~~
<span id="nav"> 
<ul>
  {% for navbar_link in page.navbar_links %}
      <span><a href={{ site.data.navbar_links | where:"name","navbar_link" }}>{{ navbar_link }}</a></span>
  {% endfor %}
</ul>
</span> 
~~~

I will just say that I have tried many variants that might make sense for the yml file and the above html file.

**Comment by kleinfreund** [comment]
So you have a `navbarlinks.yml` inside your `_data` directory?

The procedure with that would look like this:

```liquid
{% for navbar_link in site.data.navbarlinks %}
    <a href="{{ navbar_link.url }}">{{ navbar_link.name }}</a>
{% endfor %}
```

**Comment by knsam** [comment]
@kleinfreund But I don't want do that for all the entries in navbarlinks.yml, but only for those specified in the YFM variable `navbar_links`. This variable takes a list of strings at the moment.

**Comment by kleinfreund** [comment]
How is the front matter for this variable structured? It always helps to include a minimal example.

**Comment by knsam** [comment]
@kleinfreund I pointed out in my OP that it was a list of strings like so: 

    ---
    navbar_links = ["Home"]
    ---

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
