### ISSUE TITLE
Jekyll: ERROR: Failed to build gem native extension

### ISSUE THREAD

**Issue by kutec** [jekyll/jekyll-help#301]
I am trying to install Jekyll using `gem install jekyll` in Windows 8, but somehow it gives below error.

> Temporarily enhancing PATH to include DevKit...
> Building native extensions.  This could take a while...
> ERROR:  Error installing jekyll:
> ERROR: Failed to build gem native extension.
>
>    C:/Ruby193/bin/ruby.exe -r ./siteconf20150510-10840-19v5lhf.rb extconf.rb
creating Makefile

>make  clean
>Makefile:165: *** target pattern contains no `%'.  Stop.

>make
>Makefile:165: *** target pattern contains no `%'.  Stop.

>make failed, exit code 2

>Gem files will remain installed in C:/Ruby193/lib/ruby/gems/1.9.1/gems/fast-stemmer-1.0.2 for inspection.
>Results logged to C:/Ruby193/lib/ruby/gems/1.9.1/extensions/x86-mingw32/1.9.1/fast-stemmer-1.0.2/gem_make.out

**Comment by nhudacin** [comment]
+1 just got this same error

**Comment by jcontini** [comment]
+1, Windows 8, fresh Ruby 2.2.2p95 install

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
