### ISSUE TITLE
Custom Liquid Plugin for custom Syntax Highlighting - embedded code confuses Kramdown

### ISSUE THREAD

**Issue by scorcher24** [jekyll/jekyll-help#302]
I have written this plugin:

```ruby
module Jekyll
    module Tags
        class Prism < Liquid::Block
            def initialize(tag_name, text, tokens)
                @arg = text.strip
                super
            end

            def render(context)
                output = super(context)
                "<pre><code class=\"language-#{@arg}\">#{output}</code></pre>"
            end
        end
    end
end 

Liquid::Template.register_tag('prism', Jekyll::Tags::Prism)
```

This is how I use it:

```c++
{% prism cpp %}
#include <iostream>

// Hello World
int main()
{
    cout << "hello world" << endl;
    int a = 10;
}
{% endprism %}
```

Now, the problem is, that I mostly use C++ Code on my website. When I now generate this markdown with Jekyll, then all text after ```{% endprism %}``` would still be included within the ```<pre>``` Tag, because Kramdown is getting confused by ```<iostream>``` If I escape it (```\<iostream\>```), then my plugin works as expected, but my Javascript Highlighter is getting confused.

How can I solve this situation without enabling Jekyll's highlighter because this one does not work properly for me. I am on Windows and barely got Jekyll working after lots of certificate problems with gem. I am also porting an existing website which used prism.js for highlighting before and I find it kind of neat.

Another good help would be if someone can tell me how if there is a Ruby function that I can use to convert all ```<>``` to html special characters within my plugin. Is there something like htmlspecialchars from PHP? So I can have the original code in my markdown file. I am sorry for asking, I am really new to ruby and jekyll.

edit: I solved it by using CGI.escapeHTML(), but I still would like to know if there is a Jekyll way to solve it, just for learning.

**Comment by parkr** [comment]
This repository is no longer maintained. Please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
