### ISSUE TITLE
jekyll serve encountering errors

### ISSUE THREAD

**Issue by rpottsoh** [jekyll/jekyll-help#306]
Here is snapshot of the error I am receiving when I attempt to jekyll serve my site.  The site works remotely.  I am assuming I am missing something in my local setup of jekyll or ruby.  Any insight that could be offered will be appreciated.   Thanks, Ryan

C:\projects.git\AkronCodeClub.github.io>jekyll serve
WARN: Unresolved specs during Gem::Specification.reset:
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/net/http.rb:920:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certifi
cate verify failed (OpenSSL::SSL::SSLError)
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/net/http.rb:920:in`block in connect'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/net/http.rb:920:in`connect'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/net/http.rb:852:in`start'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/open-uri.rb:313:in `open_http'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/open-uri.rb:724:in`buffer_open'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/open-uri.rb:210:in `block in open_loop'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/open-uri.rb:208:in`catch'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/open-uri.rb:208:in `open_loop'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/open-uri.rb:149:in`open_uri'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/open-uri.rb:704:in `open'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/open-uri.rb:34:in`open'
        from C:/projects.git/AkronCodeClub.github.io/Gemfile:5:in `eval_gemfile'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.9.7/lib/bundler/dsl.rb:32:in`instance_eval'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.9.7/lib/bundler/dsl.rb:32:in `eval_gemfile'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.9.7/lib/bundler/dsl.rb:10:in`evaluate'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.9.7/lib/bundler/definition.rb:25:in `build'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.9.7/lib/bundler.rb:155:in`definition'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.9.7/lib/bundler.rb:118:in `setup'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:37:in`require_from_bundler'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/bin/jekyll:16:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.1.0/bin/jekyll:23:in`load'
        from C:/RailsInstaller/Ruby2.1.0/bin/jekyll:23:in `<main>'

**Comment by parkr** [comment]
This repository is no longer maintained. Please post your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum.
