### ISSUE TITLE
Excerpt sometimes turns [links][1] into links, sometimes doesn't

### ISSUE THREAD

**Issue by crummy** [jekyll/jekyll-help#307]
I have a Jekyll site hosted on github pages. On my blog page, I list every blog post with an excerpt for each. Most blog posts leave links in their raw form, like [this][1] but some link correctly.

You can see my working example here, for the article "Terry Cavanagh's Super Hexagon and VVVVVV":
http://malcolmcrum.com/blog.html
There are plenty of non-working examples, including "Nuclear Throne: A case study in player feedback"
Here's the [markup for the article with the working links in excerpt](https://raw.githubusercontent.com/crummy/crummy.github.io/master/_posts/2012-09-18-terry-cavanaghs-super-hexagon-and-vvvvvv.md) and an example of the [markup for an article with a broken link in excerpt](https://raw.githubusercontent.com/crummy/crummy.github.io/master/_posts/2014-09-29-nuclear-throne-a-case-study-in-player-feedback.md).

I tried `excerpt_separator: ""` but that seemed to disable excerpts entirely.

**Comment by kleinfreund** [comment]
We have a dedicated help forum now. I have to ask you to post your question again over at https://talk.jekyllrb.com/.

**Comment by crummy** [comment]
Thanks, I [posted there](https://talk.jekyllrb.com/t/excerpt-sometimes-turns-links-1-into-links-sometimes-doesnt/870).

**Comment by crummy** [comment]
With [gynter's](https://talk.jekyllrb.com/t/excerpt-sometimes-turns-links-1-into-links-sometimes-doesnt/870/4?u=crummy) help, I've managed to reliably reproduce this.

If footnote style links are used, and the footnote has a space prior, if an excerpt is taken of the post then links in the excerpt will not work.

**Comment by parkr** [comment]
Looks like you got it fixed.
