### ISSUE TITLE
Installation Troubleshooting Apt Command Error

### ISSUE THREAD

**Issue by radumas** [jekyll/jekyll-help#308]
On the [troubleshooting page](http://jekyllrb.com/docs/troubleshooting/) for the installation, it suggests installing `ruby 2.0.0` by running the command:

```
sudo apt-get install ruby2.0.0-dev
```

However, in `Ubuntu 14.04` the available package is `ruby2.0-dev`

EDIT: (apologies, I didn't see the "improve this page" link at the top of the troubleshooting page)

**Comment by parkr** [comment]
This repository is no longer maintained. Please post your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum.
