### ISSUE TITLE
Javascript corrupted at destination folder

### ISSUE THREAD

**Issue by DannyBen** [jekyll/jekyll-help#310]
( After this long post, I saw the repo is deprecated - someone should change [the link from the documentation](http://jekyllrb.com/docs/troubleshooting/)..... )

There seem to be something wrong in the way Jekyll copies javascripts to the site folder.

For context: I am working on Ubuntu 14 using Vagrant. My host machine is Windows 8, and I am editing with Sublime text.  My workflow is such that I have the server running while editing, if that matters. Run command is: `jekyll serve --host 0.0.0.0 --force_polling`

I have a single, small js file as `/js/site.js`

Here are the anomalies I have encountered:

**Scenario 1:**

When saving with Sublime, the generated JS file gets corrupted in one of two ways.
Either it is only partially saved (ended in the middle) or saved with many NUL characters at the end.

I made sure Sublime saves with no BOM, tried saving with Linux and Windows line endings.

Saving with vi seems to eliminate this problem.

**Scenario 2:**

This problem occurs even when saving through vi.

When I add two rows of YAML dashes on top to encourage jekyll to process it, and save the file, it saves my entire page layout (HTML) as the js file. I am pasting below the original js, and a sample of what it saves.

**Original `js/site.js`:**

```

---

---
$(document).ready( function() {
    // init Isotope
    var $grid = $('.grid').isotope({
        itemSelector: '.grid-item',
        masonry: {
            columnWidth: {{ site.tilewidth }},
            transitionDuration: '0.1s',
            isFitWidth: true
        }
    });
    // layout Isotope after each image loads
    $grid.imagesLoaded().progress( function() {
        $grid.isotope('layout');
    });

    // $('.grid').isotope({
    //  itemSelector: '.grid-item',
    //  masonry: {
    //      columnWidth: 100
    //  }
    // });
});
```

**Output: `_site/js/site.js`**

```
<!doctype html>
<html>
  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>GoGorfine</title>
  <meta name="description" content="">

  <link rel="stylesheet" href="/css/main.css">
  <link rel="canonical" href="http://gogorfine.com/js/site.js">
  <link rel="alternate" type="application/rss+xml" title="GoGorfine" href="http://gogorfine.com/feed.xml" />

  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.2.1/isotope.pkgd.min.js"></script>  
  <script src="/js/site.js"></script>  
</head>

  <body>
    <header>
    <div class="restraint">
        Hello
    </div>
</header>

    <div id='main'>
        $(document).ready( function() {
    // init Isotope
    var $grid = $('.grid').isotope({
        itemSelector: '.grid-item',
        masonry: {
            columnWidth: ,
            transitionDuration: '0.1s',
            isFitWidth: true
        }
    });
    // layout Isotope after each image loads
    $grid.imagesLoaded().progress( function() {
        $grid.isotope('layout');
    });

    // $('.grid').isotope({
    //  itemSelector: '.grid-item',
    //  masonry: {
    //      columnWidth: 100
    //  }
    // });
});


    </div>
    <footer>
    <div class="restraint">
        Hello
    </div>
</footer>

  </body>
</html>

```

**Comment by parkr** [comment]
This repository is no longer maintained. Please post your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum.
