### ISSUE TITLE
Depreciation issue with pygments

### ISSUE THREAD

**Issue by magnusmetz** [jekyll/jekyll-help#48]
Hi. I know jekyll for three day now and it seems to work fine so far. I get into it and I love the possibilities it provides to use jekyll in combination with Github pages, R, R markdown, and RStudio (see http://magnusmetz.github.io/). Just one (hopefully last) question: Everytime I call 

```
jekyll serve
```

the command does its job and parses the site but I also get a message, which confuses me: 

```
 Deprecation: The 'pygments' configuration option has been renamed to 'highlighter'. Please update your config file accordingly. The allowed values are 'rouge', 'pygments' or null.
```

What does that mean? Can you help interpret that and tell me what to do? I just want to understand what is going on. Thanks in advance for further help.

Yours,
Magnus

**Comment by Joozo** [comment]
you have to change your config file,
this line in particular. Replace pygments with highlighter and set the value you want, check the docs for the allowed values
