### ISSUE TITLE
How do I create "Edit this page" links in Jekyll?

### ISSUE THREAD

**Issue by erlend-sh** [jekyll/jekyll-help#5]
A few Jekyll docs pages I've visited have a handy "Edit" link that takes me to that page's file on GitHub, so I can edit it directly or make a pull request.

Example 1: Top right, "Improve this doc"
http://ionicframework.com/docs/api/directive/ionTabs/

Example 2: Top right, "Edit"
http://sendgrid.com/docs/API_Reference/index.html

Is there a default way of achieving this in Jekyll?

**Comment by Strangehill** [comment]
For future reference, {{ page.path }} and {{ page.relative_path }} now give the same, relative, path in collection documents (as of 3.0)
