### ISSUE TITLE
ERROR when installing jekyll

### ISSUE THREAD

**Issue by Vercryger** [jekyll/jekyll-help#55]
When i trying to install jekyll with <code>$ gem install jekyll</code> i got this:

```
ERROR:  Loading command: install (LoadError)
    cannot load such file -- zlib
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```

I have already installed this package:

```

$ ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [i686-linux]
$ gem -v
2.2.2
$ sudo update-alternatives --config ruby
There is only one alternative in link group ruby: /usr/bin/ruby1.9.1
Nothing to configure.
$ sudo update-alternatives --config gem
There is only one alternative in link group gem: /usr/bin/gem1.9.1
Nothing to configure.
```

**Comment by thomasdola** [comment]
how did y remove all previously installed rubies on your OS???
need help with that... thank y...

**Comment by Vercryger** [comment]
In my case, i did that just removing from my ubuntu synaptic any gem and ruby too. Then i deleted all my gems from RVM, i followed [this guide](http://stackoverflow.com/questions/4907668/removing-all-installed-gems-and-starting-over).
Remember, you have to have Node previously installed for Jekyll.
