### ISSUE TITLE
Are there any web development shops with experience building Jekyll sites? 

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-help#60]
Obviously it's just HTML + Liquid, so there's no language to learn, per se, but are there any agencies that have done Jekyll sites in the past?

Alternatively, are there any freelance developers/designers who specialize in Jekyll?

**Comment by CurbStop** [comment]
Our company uses Jekyll as an internal message board, where we can share news about the industry and changes to laws. It is a very practical solution for one-way delivery of content which essentially forgoes the need to maintain a full fledged web solution.

**Comment by BraydenGirard** [comment]
If anyone is still looking for a development agency that specializes in Jekyll you can contact us through our website https://www.daydreamdev.com. We specialize in building Jekyll websites along with our easy to manage CMS system. We are based out of Ottawa and are available for free consultations.
