### ISSUE TITLE
Can't start server with jekyll 2.0.3 on windows.

### ISSUE THREAD

**Issue by FernandoBasso** [jekyll/jekyll-help#64]
When I type:

```
D:\Fernando\prog\fernandobasso.github.io>jekyll server --watch
Configuration file: D:/Fernando/prog/fernandobasso.github.io/_config.yml
            Source: D:/Fernando/prog/fernandobasso.github.io
       Destination: D:/Fernando/prog/fernandobasso.github.io/_site
      Generating...
                    done.
jekyll 2.0.3 | Error:  undefined method `_log' for Listen::Adapter::Windows:Class
```

Google didn't help this time.

ruby 1.9.3p545 (2014-02-24) [i386-mingw32]

gem 1.8.28

**Comment by rsb12php** [comment]
Well, i tried all! But, fail :(

**Comment by parkr** [comment]
@rsb12php You're using `bundle exec jekyll serve` on the latest version of Jekyll?

**Comment by rsb12php** [comment]
@parkr it's all right now, but thak you

**Comment by rsb12php** [comment]
@parkr I using Windows 8
jekyll - Auto regeneration is not working!
Do you can help me?

**Comment by anegronweb** [comment]
I had the same problem. I add "highlighter: rouge" and it work
