### ISSUE TITLE
Working, official-unofficial Atom feed code

### ISSUE THREAD

**Issue by ndarville** [jekyll/jekyll-help#7]
I currently use [this](https://github.com/ndarville/ndarville.github.io/blob/master/feed/index.xml) feed code for [my blog](http://ndarville.github.io/). Unfortunately, it doesn’t seem to work in readers (ndarville/ndarville.github.io#11).

Finding the right feed code is a terrible experience I wouldn’t wish upon my worst enemy, and I recall how long it took me to get it to work for the static Blogofile CMS.

Can we establish a working official-unofficial Jekyll feed code that people can use, and which can be improved upon in one central place, should any new bugs be found?

## Decisions

- [x] `{{ site.baseurl }}` vs. `{{ site.url }}` w/r/t SSL
- [x] `xml_escape` vs. `CDATA`
- [x] Filename: `/atom/index.xml`, `atom.xml`, `feed.atom`, etc.

**Comment by parkr** [comment]
We have https://github.com/jekyll/jekyll-feed now. I believe Ben Balter is working on bringing it into GitHub Pages if it isn't already there.
