### ISSUE TITLE
Running multiple Jekyll Servers?

### ISSUE THREAD

**Issue by andysanchez** [jekyll/jekyll-help#85]
Hello, I'm extremely pleased with running Jekyll on my own server so far. I was thinking about setting up a few sites for my co-workers to play around with and was wondering what suggestions there are on hosting multiple Jekyll sites?

Ideally, I'd want to use the same EC2 box to run 3 or 4 Jekyll instances. I'd assume I just tell it to run on separate ports and handle the port mapping with virtual hosts?

I couldn't find any info on this and figured this is the best way to answer, thanks for the pointers :-)

**Comment by villesau** [comment]
For me running multiple jekyll servers is valid need, because i need to compare and develop multiple different layouts/sites at the same time (to pick the best) and because jekyll has easy bundled server with it, i' like to use it instead of hacking my own server up just for that purpose.

**Comment by parkr** [comment]
This issue has been migrated to https://talk.jekyllrb.com/t/running-multiple-jekyll-servers/652 . Please continue discussion there.
