### ISSUE TITLE
Jekyll and Compass

### ISSUE THREAD

**Issue by SimonWpt** [jekyll/jekyll-help#98]
I installed jekyll on Windows and everything works fine...

... until I tried to include compass. 

``` SASS
@import "compass"
```

I get the error message `File to import not found or unreadable: compass. (Sass::SyntaxError)` But compass is installed!

Any ideas, why jekyll doesn't find compass?

**Comment by ajkochanowicz** [comment]
Where did this end up? Can one add muiltiple sass load_paths in Jekyll's current state?

**Comment by parkr** [comment]
> Can one add muiltiple sass load_paths

Yes!

**Comment by ajkochanowicz** [comment]
That's good!

Is this documented somewhere? I've tried a few times but it's not working for me.

I've also looked at PRs. They seem to indicate you just add a YAML array to `load_paths` in _config.yml. Is there more to it than that?

Thanks

**Comment by ajkochanowicz** [comment]
Ah, I think I got it.

    sass:
      load_paths:
       - "_sass"
       - "path1"
       - "path2"
